// CousinPCMS.React/src/pages/Product.tsx
import React, {useState, useEffect} from 'react';
import {useNavigate} from 'react-router';
import {Tabs, Button, Popconfirm} from 'antd';
import {QuestionCircleOutlined} from '@ant-design/icons';
import ProductDetails from '../components/product/ProductDetails';
import {deleteProduct} from '../services/ProductService';
import {showNotification} from '../services/DataService';
import SKUsList from '../components/product/SKUsList';

const {TabPane} = Tabs;

const Product: React.FC = () => {
  const [activeTab, setActiveTab] = useState<string>('1');
  const [deleteLoading, setDeleteLoading] = useState<boolean>(false);
  const [productId, setProductId] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const productIdFromSession = sessionStorage.getItem('productId') || '3024';
    if (productIdFromSession) {
      setProductId(productIdFromSession);
    } else {
      showNotification('error', 'Product ID not found. Please select a product.');
      navigate('/home');
    }
  }, [navigate]);

  const handleCancel = () => {
    navigate('/home');
  };

  const handleDelete = async () => {
    if (!productId) {
      showNotification('error', 'Product ID is missing.');
      return;
    }
    setDeleteLoading(true);
    try {
      const response = await deleteProduct(Number(productId));
      if (response.isSuccess) {
        showNotification('success', 'Product Successfully Deleted');
        sessionStorage.removeItem('productId');
        sessionStorage.removeItem('itemNumber');
        sessionStorage.removeItem('skuId');
        navigate('/home');
      } else {
        showNotification('error', response.exceptionInformation || 'Product Deletion Failed');
      }
    } catch (err: unknown) {
      console.error('Error deleting product:', err);
      showNotification('error', 'Something went wrong during deletion.');
    } finally {
      setDeleteLoading(false);
    }
  };

  const handleSave = () => {
    showNotification('info', 'Save functionality is not implemented in this component.');
  };

  const tabBarExtraContent = (
    <div className="flex gap-x-3 mb-2 mr-4">
      <Button onClick={handleCancel}>Cancel</Button>
      <Popconfirm title="Are you sure delete this product?" onConfirm={handleDelete} okText="Yes" cancelText="No" placement="left" icon={<QuestionCircleOutlined style={{color: 'red'}} />}>
        <Button danger loading={deleteLoading}>
          Delete
        </Button>
      </Popconfirm>
      <Button type="primary" loading={deleteLoading} onClick={handleSave}>
        Save
      </Button>
    </div>
  );

  return (
    <div className="bg-white shadow-cousins-box rounded-lg m-5">
      <div className="p-4 pb-1">
        <span className="text-sm font-medium">Product Form</span>
        <Tabs activeKey={activeTab} onChange={setActiveTab} tabBarExtraContent={tabBarExtraContent} className="product-tabs">
          <TabPane tab="Product Details" key="1">
            <ProductDetails />
          </TabPane>
          <TabPane tab="SKUs" key="2">
            <SKUsList />
          </TabPane>
        </Tabs>
      </div>
    </div>
  );
};

export default Product;

// CousinPCMS.Angular/src/app/components/product/product.component.ts
import { Component, ViewChild } from '@angular/core';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzTabsModule } from 'ng-zorro-antd/tabs';
import { DataService } from '../../shared/services/data.service';
import { Router } from '@angular/router';
import { HomeService } from '../home/home.service';
import { ProductDetailsComponent } from './product-details/product-details.component';
import { Subscription } from 'rxjs';
import { SkusListComponent } from './skus-list/skus-list.component';
import { ProductsService } from './products.service';
import { ProductRequest, ProductResponse, ProductUpdateResponse } from '../../shared/models/productModel';
import { NzSpinModule } from 'ng-zorro-antd/spin';

@Component({
  selector: 'cousins-product',
  imports: [ NzTabsModule,  // ✅ Import Tabs
             NzButtonModule,
             ProductDetailsComponent,
             SkusListComponent,
             NzSpinModule
            ],
  templateUrl: './product.component.html',
  styleUrl: './product.component.css'
})
export class ProductComponent {

  activeTab: number = 0; // Default tab
  deleteLoading: boolean = false;
  loading: boolean = true;
  btnLoading: boolean = false;
  productData!: any;
  
 private productSubscription!: Subscription;
 @ViewChild(ProductDetailsComponent) productDetailsComp!: ProductDetailsComponent;

  constructor(private dataService : DataService, 
    private readonly router: Router, private productService : ProductsService) {
  }

  ngOnInit(): void {  
    this.getProductById();
   
  }

  getProductById() {
    const productId = sessionStorage.getItem('productId') || '';
    if (productId) {
    this.productService.getProductById(productId).subscribe({
      next: (response: ProductResponse) => {
        if (response.isSuccess) {
          this.productData = response.value[0];
        } else {
          this.dataService.ShowNotification('error', '', 'Failed To Load Data');
        }
        this.loading = false;
      },
      error: (err) => {
        this.loading = false;
        if (err?.error) {
          this.dataService.ShowNotification('error', '', err.error.title);
        } else {
          this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      },
    });
    } else {
      this.dataService.ShowNotification('error', '', 'Please select product name from home page');
    }
  }

  cancle() {
    this.router.navigate(['/home']);
  }

  delete() {
    const proData = this.productDetailsComp.getFormData();
    this.deleteLoading = true;
    this.productService.deleteProduct(proData.akiProductID).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.dataService.ShowNotification('success', '', 'Product Successfully Deleted');
          sessionStorage.removeItem('productId');
          sessionStorage.removeItem('itemNumber');
          sessionStorage.removeItem('skuId');
          this.router.navigate(['/home']);
        } else {
          this.dataService.ShowNotification('error', '', 'Product Details Failed Deleted');
        }
        this.deleteLoading = false;
      },
      error: (err) => {
        this.deleteLoading = false;
        if (err?.error) {
          this.dataService.ShowNotification('error', '', err.error.title);
        } else {
          this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      }
    });

  }
 
  saveDetails () {
     this.productDetailsComp.productForm.markAllAsTouched();

     if (!this.productDetailsComp.productForm.valid) {
       this.dataService.ShowNotification('error', '', 'Please fill in all required fields.');
       return;
     }
 
     // Get data from both components (if forms are valid)
     const productData = this.productDetailsComp.getFormData();

     if (productData.aki_Layout_Template) {
        productData.akiProductPrintLayoutTemp = true;
     }

     const req: ProductRequest = {
      ...productData,
      categoryName: productData.category_Name,
    };

    delete (req as any).category_Name;
    delete (req as any).akiProductDescription;

     this.btnLoading = true;
     this.productService.updateProduct(req).subscribe({
       next: (response: ProductUpdateResponse) => {
        if (response.isSuccess) {
          this.dataService.ShowNotification('success', '', 'Product Details Updated Successfully');
          this.router.navigate(['/home']);
        } else {
          this.dataService.ShowNotification('error', '', "Product Details Failed Updated");
        }
         this.btnLoading = false;
       },
       error: (err) => {
          this.btnLoading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
       }
     });
  }

  ngOnDestroy() {
    if (this.productSubscription) {
      this.productSubscription.unsubscribe();
    }
  }

}

<div class="bg-white rounded-lg m-5">
  <label class="px-4 pt-3 mb-0 [color:var(--color-primary-font)] text-sm font-medium">Product Form</label>

  <nz-spin [nzSpinning]="loading">
    <!-- Tabs -->
    <nz-tabset [(nzSelectedIndex)]="activeTab" [nzTabBarExtraContent]="extraTemplate">
      <nz-tab nzTitle="Product Details">
        <cousins-product-details [productData]="productData" [isSetAttributslist]="isSetAttributslist"></cousins-product-details>
      </nz-tab>

      <nz-tab nzTitle="SKUs">
        <cousins-skus-list></cousins-skus-list>
      </nz-tab>
    </nz-tabset>

    <ng-template #extraTemplate>
      <div class="flex gap-x-3 mb-2">
        <button nz-button nzType="default" class="" (click)="cancel()">Close</button>
        <!-- <button
          nz-button
          nzType="default"
          class=""
          [nzLoading]="deleteLoading"
          nz-popconfirm
          [nzPopconfirmTitle]="'Are you sure you want to delete this product?'"
          (nzOnConfirm)="delete()"      
          [nzIcon]="iconTpl"
          nzPopconfirmPlacement="left"
        >
          Delete
        </button> -->
        <button nz-button nzType="primary" class="text-white me-3" [nzLoading]="btnLoading" (click)="saveDetails()">Save</button>
        <ng-template #iconTpl>
          <nz-icon nzType="question-circle-o" class="text-danger me-2" />
        </ng-template>
      </div>
    </ng-template>
  </nz-spin>
</div>
