// CousinPCMS.React/src/components/product/SKUsList.tsx
import {useState, useEffect} from 'react';
import {Table, Checkbox, Spin} from 'antd';
import type {TableProps} from 'antd/es/table';
import {useNotification} from '../../hook/useNotification';
import type {SKuList, SkuListResponse} from '../../models/skusModel';
import {getSkuByProductId} from '../../services/HomeService';
import {getSessionItem, setSessionItem} from '../../services/DataService';

const SKUsList = () => {
  const [loading, setLoading] = useState<boolean>(true);
  const [skusList, setSkusList] = useState<SKuList[]>([]);
  const [selectedRow, setSelectedRow] = useState<SKuList | null>(null);
  const [productId] = useState<string | null>(getSessionItem('productId') || getSessionItem('tempProductId'));
  const notify = useNotification();

  useEffect(() => {
    const loadSkuForProduct = async () => {
      if (!productId) {
        setLoading(false);
        setSkusList([]);
        return;
      }
      setLoading(true);
      setSelectedRow(null);
      try {
        const data: SkuListResponse = await getSkuByProductId(Number(productId));
        if (data.isSuccess && data.value) {
          const activeSkus = data.value.filter((sku: SKuList) => sku?.akiSKUIsActive).sort((a, b) => Number(a.akiListOrder || 0) - (Number(b.akiListOrder) || 0));
          setSkusList(activeSkus);
        } else {
          notify.info(data.exceptionInformation || 'No SKU data found or request failed.');
          setSkusList([]);
        }
      } catch (error) {
        notify.error(error instanceof Error ? error.message : 'Something went wrong while fetching SKUs.');
        setSkusList([]);
      } finally {
        setLoading(false);
      }
    };
    loadSkuForProduct();
  }, [productId, notify]);

  const handleRowSelect = (record: SKuList) => {
    setSelectedRow((prev: SKuList | null) => (prev?.akiitemid === record.akiitemid ? null : record));
    if (record.akiitemid !== selectedRow?.akiitemid) {
      setSessionItem('itemNumber', record.akiitemid || '');
      setSessionItem('skuId', String(record.akiSKUID || ''));
    } else {
      sessionStorage.removeItem('itemNumber');
      sessionStorage.removeItem('skuId');
    }
  };

  const columns: TableProps<SKuList>['columns'] = [
    {
      title: 'Sku Name',
      dataIndex: 'skuName',
      width: 200,
      ellipsis: true,
      sorter: (a, b) => a.skuName.localeCompare(b.skuName),
    },
    {
      title: 'MFR Ref No',
      dataIndex: 'akiManufacturerRef',
      ellipsis: true,
      width: 190,
      sorter: (a, b) => a.akiManufacturerRef.localeCompare(b.akiManufacturerRef),
    },
    {
      title: 'Item No',
      dataIndex: 'akiitemid',
      width: 120,
      sorter: (a, b) => (Number(a.akiitemid) || 0) - (Number(b.akiitemid) || 0),
    },
    {
      title: 'List Order',
      dataIndex: 'akiListOrder',
      width: 100,
      align: 'right',
      sorter: (a, b) => (Number(a.akiListOrder) || 0) - (Number(b.akiListOrder) || 0),
    },
    {
      title: 'Obsolete',
      dataIndex: 'akiObsolete',
      width: 90,
      align: 'center',
      render: (isObsolete) => <Checkbox checked={isObsolete} disabled />,
    },
    {
      title: 'Unavailable',
      dataIndex: 'salesBlocked',
      width: 100,
      align: 'center',
      render: (isBlocked) => <Checkbox checked={isBlocked} disabled />,
    },
    {
      title: 'Web Active',
      dataIndex: 'akiWebActive',
      align: 'center',
      render: (isWebActive) => <Checkbox checked={isWebActive} disabled />,
      width: 100,
    },
    {
      title: 'Cat Active',
      dataIndex: 'akiSKUIsActive',
      width: 90,
      align: 'center',
      render: (isActive) => <Checkbox checked={isActive} disabled />,
    },
    {title: 'TemplateID', dataIndex: 'akiTemplateID', width: 100, align: 'center'},
    {
      title: 'AltSku Name',
      dataIndex: 'akiAltSKUName',
      ellipsis: true,
      width: 180,
      sorter: (a, b) => a.akiAltSKUName.localeCompare(b.akiAltSKUName),
    },
    {
      title: 'Comm Code',
      dataIndex: 'akiCommodityCode',
      width: 120,
      sorter: (a, b) => (Number(a.akiCommodityCode) || 0) - (Number(b.akiCommodityCode) || 0),
    },
  ];

  return (
    <div className="px-4">
      <Spin spinning={loading}>
        <Table
          columns={columns}
          scroll={{x: 1100}}
          dataSource={skusList}
          rowKey="akiitemid"
          size="small"
          bordered
          pagination={false}
          className="no-header-scroll"
          onRow={(record) => ({
            onClick: () => handleRowSelect(record),
            className: record.akiitemid === selectedRow?.akiitemid ? 'selected-row' : '',
          })}
          showSorterTooltip={false}
        />
      </Spin>
    </div>
  );
};

export default SKUsList;

// CousinPCMS.Angular/src/app/components/product/skus-list/skus-list.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzTableModule } from 'ng-zorro-antd/table';
import { Subscription } from 'rxjs';
import { HomeService } from '../../home/home.service';
import { SKuList, SkuListResponse } from '../../../shared/models/skusModel';
import { DataService } from '../../../shared/services/data.service';

interface ItemData {
  name: string;
  age: number;
  address: string;
}

@Component({
  selector: 'cousins-skus-list',
  imports: [
    NzTableModule,
    FormsModule,
    NzCheckboxModule,
    NzIconModule
  ],
  templateUrl: './skus-list.component.html',
  styleUrl: './skus-list.component.css'
})
export class SkusListComponent {
  loading: boolean = true;
  skusList: SKuList[] = [];
  selectedRow: any = null; // Store the selected row
  private skusSubscription!: Subscription;

  constructor(private homeService: HomeService, private dataService: DataService) {}

  ngOnInit(): void {
    this.loadSkuForProduct();
  }

  loadSkuForProduct() {
    const productId = sessionStorage.getItem('productId') || '';
        this.homeService.getSkuByProductId(+productId).subscribe({
          next: (data: SkuListResponse) => {
            if (data.isSuccess) {
                if (data && data.value.length > 0) {
                  this.skusList = data.value.filter((res: SKuList) => res?.akiSKUIsActive);
                 } 
                // else {
                //   this.dataService.ShowNotification('error', '', "No Data");
                // }
            } 
            else {
              this.dataService.ShowNotification('error', '', "No Data");
            }
            this.loading = false;
          },
          error: () => { 
            this.loading = false;
            this.dataService.ShowNotification('error', '', "Something went wrong");
          }
        });
    } 

  // Handle Row Click to Select/Unselect
  onRowSelect(row: any): void {
    this.selectedRow = row === this.selectedRow ? null : row;
  }

  // Add Class to Selected Rows
  setRowClass = (row: any) => row.selected ? 'selected-row' : '';

  ngOnDestroy() {
    if (this.skusSubscription) {
      this.skusSubscription.unsubscribe();
    }
  }

}

<div class="px-4 pt-1">
  <nz-table #headerTable [nzData]="skusList" nzSize="small" nzBordered [nzShowPagination]="false" [nzLoading]="loading"
    [nzFrontPagination]="false" class="no-header-scroll">
    <thead>
      <tr>
        <th nzWidth="40px"></th>
        <th nzWidth="200px">Sku Name</th>
        <th nzWidth="200px">ManufacturerRef</th>
        <th nzWidth="100px">ITEM_NUMBER</th>
        <th nzWidth="100px">List Order</th>
        <th nzWidth="60px">Obsolete</th>
        <th nzWidth="60px">Unavailable</th>
        <th nzWidth="60px">Cat Active</th>
        <th nzWidth="90px">TemplateID</th>
        <th nzWidth="150px">AltSku Name</th>
        <th nzWidth="100px">Commodity Code</th>
      </tr>
    </thead>
    <tbody>
      @for (data of headerTable.data; track $index) {
      <tr (click)="onRowSelect(data)" [class.selected-row]="selectedRow === data">

        <!-- Play Icon for Row Selection -->
        @if(selectedRow === data) {
        <td (click)="onRowSelect(data)">
          <nz-icon nzType="caret-right" nzTheme="outline" style="font-size: 16px;" />
        </td>
        } @else {
        <td></td>
        }
        <td>{{ data.skuName }}</td>
        <td>{{ data.akiManufacturerRef }}</td>
        <td>{{ data.akiitemid }}</td>
        <td>{{ data.akiListOrder }}</td>
        <td><label nz-checkbox [(ngModel)]="data.akiObsolete" [disabled]="true"></label></td>
        <td><label nz-checkbox [(ngModel)]="data.salesBlocked" [disabled]="true"></label></td>
        <td><label nz-checkbox [(ngModel)]="data.akiSKUIsActive" [disabled]="true"></label></td>
        <td>{{ data.akiTemplateID }}</td>
        <td>{{ data.akiAltSKUName }}</td>
        <td>{{ data.akiCommodityCode }}</td>
      </tr>
      }
    </tbody>
  </nz-table>
</div>
