// CousinPCMS.React/src/App.tsx
import {Button} from 'antd';
import {Outlet} from 'react-router';
import Header from './components/shared/Header';

const App = () => {
  return (
    <>
      
      <Header />
      <Outlet />
      <Button type="primary">Primary</Button>
      <h1>Footer</h1>
    </>
  );
};

export default App;

// CousinPCMS.Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from "./components/shared/header/header.component";
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'cousins-root',
  imports: [HeaderComponent,RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'cousins';
}

<cousins-header></cousins-header>

<router-outlet></router-outlet>
