// CousinPCMS.Angular/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { TreeViewComponent } from './tree-view/tree-view.component';
import { ProductDisplayComponent } from './product-display/product-display.component';
import { SkuDisplayComponent } from './sku-display/sku-display.component';

@Component({
  selector: 'cousins-home',
  imports: [TreeViewComponent, ProductDisplayComponent, SkuDisplayComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  selectedCategory: string = '';
  selectedProductId: string = '';

  onCategorySelected(categoryId: string) {
    this.selectedCategory = categoryId;
    this.selectedProductId = '';
  }

  onProductSelected(productId: string) {
    this.selectedProductId = productId;
  }

}

<!-- <div class="grid grid-cols-12">
  <div class="col-span-6">
    <div class="grid grid-cols-12">
      <div class="col-span-6 m-4 p-2 bg-white rounded-md">
        <cousins-tree-view (categorySelected)="onCategorySelected($event)" ></cousins-tree-view>
      </div>
      <div class="col-span-6 m-4 p-2 bg-white rounded-md">
        <cousins-product-display [selectedCategory]="selectedCategory"></cousins-product-display>
      </div>
    </div>
  </div>
  <div class="col-span-6 m-4 p-2 bg-white rounded-md">
   <cousins-sku-display></cousins-sku-display>
  </div>
</div> -->




<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-4 p-4">
  <!-- Left Section -->
  <div class="lg:col-span-6">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- Category Tree -->
      <div class="p-4 bg-white rounded-md shadow-md tree-view-scroll">
        <cousins-tree-view (categorySelected)="onCategorySelected($event)"></cousins-tree-view>
      </div>
      <!-- Product Display -->
      <div class="p-4 bg-white rounded-md shadow-md card">
        <cousins-product-display [selectedCategory]="selectedCategory" (productSelected)="onProductSelected($event)"></cousins-product-display>
      </div>
    </div>
  </div>

  <!-- Right Section -->
  <div class="lg:col-span-6 p-4 bg-white rounded-md shadow-md card">
    <cousins-sku-display [selectedProductId]="selectedProductId"></cousins-sku-display>
  </div>
</div>

// CousinPCMS.React/src/pages/Home.tsx
import {useState} from 'react';
import ProductDisplay from '../components/home/ProductDisplay';
import TreeView from '../components/home/TreeView';
import SkusDisplay from '../components/home/SkusDisplay';

const Home = () => {
  const [selectedCategory, setSelectedCategory] = useState<string>('');
  const [selectedProductId, setSelectedProductId] = useState<number | undefined>(undefined);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-x-4 m-4 mb-0">
      <div className="lg:col-span-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-4">
          <div className="p-2 bg-white rounded-md shadow-cousins-box mb-0 min-h-[calc(100vh-80px)]">
            <TreeView onCategorySelected={(categoryId) => setSelectedCategory(categoryId?.toString() || '')} />
          </div>
          <div className="p-2 bg-white rounded-md shadow-cousins-box mb-0 min-h-[calc(100vh-80px)] ">
            <ProductDisplay selectedCategory={selectedCategory} onProductSelected={setSelectedProductId} />
          </div>
        </div>
      </div>
      <div className="lg:col-span-6 p-2 bg-white rounded-md shadow-cousins-box mb-0 min-h-[calc(100vh-80px)]">
        <SkusDisplay selectedProductId={selectedProductId} selectedCategory={selectedCategory} />
      </div>
    </div>
  );
};

export default Home;
