// CousinPCMS.Angular/src/app/components/skus/attribute-multi-upload/attribute-multi-upload.component.ts
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {DataService} from '../../../shared/services/data.service';
import {SkusService} from '../skus.service';
import {NzSpinModule} from 'ng-zorro-antd/spin';
import {Router, RouterLink} from '@angular/router';
import {NzButtonModule} from 'ng-zorro-antd/button';
import {ApiResponse} from '../../../shared/models/generalModel';
import {AttributeModel} from '../../../shared/models/attributeModel';
import {AttributeValueModel} from '../../../shared/models/attributesModel';
import {NzCheckboxModule} from 'ng-zorro-antd/checkbox';
import {NzTableModule} from 'ng-zorro-antd/table';
import { LikedSkuModel } from '../../../shared/models/skusModel';

@Component({
  selector: 'cousins-attribute-multi-upload',
  imports: [FormsModule, NzSpinModule, NzButtonModule, NzCheckboxModule, NzTableModule, RouterLink],
  templateUrl: './attribute-multi-upload.component.html',
  styleUrl: './attribute-multi-upload.component.css',
})
export class AttributeMultiUploadComponent {
  loading: boolean = false;
  btnLoading: boolean = false;
  attributeNames?: any;
  headers: string[] = [];
  attributeList: AttributeValueModel[] = [];
  // Group values by attributeName
  groupedValues: {[key: string]: any[]} = {};
  rowsArray: number[] = [];

  allChecked = false;

  constructor(private skusService: SkusService, private dataService: DataService, private route: Router) {}

  ngOnInit(): void {
    const stored = sessionStorage.getItem('attributeNames');
    this.attributeNames = stored ? JSON.parse(stored) : [];
    this.headers = this.attributeNames;
    this.loadAttributes();
  }

  loadAttributes(): void {
    this.loading = true;
    const req = {
      attributeNames: this.attributeNames,
    };
    this.skusService.getAttributeValuesByListofNames(req).subscribe({
      next: (reponse: ApiResponse<AttributeValueModel[]>) => {
        if (reponse.isSuccess) {
          if (reponse.value && reponse.value.length > 0) {
            this.attributeList = reponse.value;
            if (this.attributeList.length > 0) {
              this.headers.forEach((header) => {
                this.groupedValues[header] = this.attributeList.filter((val) => val.attributeName === header);
              });
              this.headers = Object.keys(this.groupedValues);
              const maxRows = Math.max(...this.headers.map((h) => this.groupedValues[h]?.length || 0));
              this.rowsArray = Array.from({length: maxRows}, (_, i) => i);
            }
          } else {
            this.dataService.ShowNotification('error', '', 'No Data');
          }
        } else {
          this.dataService.ShowNotification('error', '', 'Failed To Load Data');
        }
        this.loading = false;
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
        this.loading = false;
      },
    });
  }

  getMaxRows(): number {
    return Math.max(...this.headers.map((h) => this.groupedValues[h]?.length || 0));
  }

  cancel() {
    sessionStorage.removeItem('attributeNames');
    this.route.navigate(['/skus']);
  }

  changeLinkedAttributeValues(event: boolean, data: any) {
    const req: LikedSkuModel = {
      akiItemNo: sessionStorage.getItem('itemNumber') || '',
      akiAttributeName: data.attributeName,
      akiAttributeValue: data.attributeValue,
      akiLink: data.attributeValueLinkedToSKU,
    };

    this.skusService.addUpdateSKULinkedAttribute(req).subscribe({
      next: (reponse: ApiResponse<LikedSkuModel>) => {
        if (reponse.isSuccess) {
          if (reponse.value) {
            this.dataService.ShowNotification('success', '', 'Attribute Value Successfully Updated');
          }
        } else {
          this.dataService.ShowNotification('error', '', reponse.exceptionInformation);
        }
        this.loading = false;
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
        this.loading = false;
      },
    });
  }
}

<div class="bg-white rounded-lg shadow-md m-5">
  <nz-spin [nzSpinning]="loading">
    <div class="flex justify-between items-center p-4 pb-1">
      <span class="text-sm font-medium">Attribute Multi Upload Form</span>
      <div class="flex gap-x-3">
        <button nz-button nzType="default" (click)="cancel()" class="">Cancel</button>
        <button nz-button nzType="primary" [routerLink]="'/attributes/add'">New Value</button>
      </div>
    </div>
    <hr class="mt-2 mb-1 border-light-border" />

    <div class="p-4">
      <nz-table #headerTable [nzData]="rowsArray" nzSize="small" nzBordered [nzShowPagination]="false" [nzFrontPagination]="false" [nzScroll]="{y: '660px'}">
        <thead>
          <tr>
            @for ( header of headers; track $index) {
            <th>
              {{ header }}
            </th>
            <th>Select</th>
            }
          </tr>
        </thead>
        <tbody>
          @for (data of headerTable.data; track $index) {
          <tr>
            @for (header of headers; track $index) {
            <td>
              {{ groupedValues[header][data]?.attributeValue || '' }}
            </td>
            @if (groupedValues[header][data]?.attributeValue) {
            <td>
              <label nz-checkbox [(ngModel)]="groupedValues[header][data].attributeValueLinkedToSKU" (ngModelChange)="changeLinkedAttributeValues($event, groupedValues[header][data])"></label>
            </td>
            } @else {
            <td></td>
            } }
          </tr>
          }
        </tbody>
      </nz-table>

      <!-- <table class="min-w-full border border-gray-200">
        <thead class="bg-gray-100">
          <tr>
            @for ( header of headers; track $index) {
            <th class="p-2 border border-gray-300">
              {{ header }}
            </th>
            <th class="p-2 border border-gray-300">Select</th>
            }
          </tr>
        </thead>
        <tbody>
          @for ( i of rowsArray ;track $index) {
          <tr>
            @for (header of headers; track $index) {
            <td class="p-2 border border-gray-300">
              {{ groupedValues[header][i]?.attributeValue || '' }}
            </td>
            <td class="p-2 border border-gray-300"><label nz-checkbox></label></td>
            }
          </tr>
          }
          <tr></tr>
        </tbody>
      </table> -->
    </div>
  </nz-spin>
</div>

// CousinPCMS.React/src/components/attribute/AttributeMultiUpload.tsx
import {useState, useEffect, useCallback} from 'react';
import {useNavigate, Link} from 'react-router';
import {Table, Checkbox, Spin, Button} from 'antd';
import type {TableProps} from 'antd/es/table';
import type {CheckboxChangeEvent} from 'antd/es/checkbox';

import {getAttributeValuesByListofNames, addUpdateSKULinkedAttribute} from '../../services/SkusService';
import {extractUserMessage} from '../../services/DataService';
import type {ApiResponse} from '../../models/generalModel';
import type {AttributeValueModel} from '../../models/attributesModel';
import type {LikedSkuModel} from '../../models/skusModel';
import {useNotification} from '../../contexts.ts/useNotification';

interface GroupedValues {
  [attributeName: string]: ExtendedAttributeValueModel[];
}

interface ExtendedAttributeValueModel extends AttributeValueModel {
  key: string;
  attributeValueLinkedToSKU: boolean;
}

interface TableRowData {
  key: number;
  [attributeName: string]: string | boolean | number | null | ExtendedAttributeValueModel | undefined;
}

const AttributeMultiUpload = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [attributeNames, setAttributeNames] = useState<string[]>([]);
  const [tableDataSource, setTableDataSource] = useState<TableRowData[]>([]);
  const notify = useNotification();

  const navigate = useNavigate();

  const loadAttributeValues = useCallback(async (names: string[]) => {
    setLoading(true);
    setTableDataSource([]);
    try {
      const req = {attributeNames: names};
      const response: ApiResponse<AttributeValueModel[]> = await getAttributeValuesByListofNames(req);
      if (response.isSuccess && response.value) {
        if (response.value.length > 0) {
          const attributeList: ExtendedAttributeValueModel[] = response.value.map((val: AttributeValueModel, index: number) => ({
            ...val,
            attributeValueLinkedToSKU: val.attributeValueLinkedToSKU ?? false,
            key: `${val.attributeName}-${val.attributeValue}-${index}`,
          }));

          const groups: GroupedValues = {};
          names.forEach((name) => {
            groups[name] = attributeList.filter((val) => val.attributeName === name);
          });

          const maxRowCount = Math.max(0, ...names.map((h) => groups[h]?.length || 0));
          const dataSource: TableRowData[] = [];
          for (let i = 0; i < maxRowCount; i++) {
            const row: TableRowData = {key: i};
            names.forEach((header) => {
              const item = groups[header]?.[i];
              row[`${header}_value`] = item?.attributeValue ?? null;
              row[`${header}_checked`] = item?.attributeValueLinkedToSKU ?? false;
              row[`${header}_item`] = item ? {...item} : null;
            });
            dataSource.push(row);
          }
          setTableDataSource(dataSource);
        } else {
          extractUserMessage('No attribute values found for the selected names.');
        }
      } else {
        extractUserMessage('Failed To Load Attribute Values');
      }
    } catch (error) {
      console.error('Error loading attribute values:', error);
      extractUserMessage('Something went wrong loading attribute values.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const storedNames = sessionStorage.getItem('attributeNames');
    const names = storedNames ? JSON.parse(storedNames) : [];
    if (names.length === 0) {
      extractUserMessage('No attribute names found in session storage.');
      navigate(-1);
      return;
    }
    setAttributeNames(names);
    loadAttributeValues(names);
  }, [loadAttributeValues, navigate]);

  const handleCancel = () => {
    sessionStorage.removeItem('attributeNames');
    navigate('/skus');
  };

  const handleCheckboxChange = async (event: CheckboxChangeEvent, rowIndex: number, header: string) => {
    const isChecked = event.target.checked;
    const item = tableDataSource[rowIndex][`${header}_item`] as ExtendedAttributeValueModel | null;
    if (!item) {
      console.error('Could not find item data for checkbox change.');
      return;
    }
    const updatedDataSource = [...tableDataSource];
    updatedDataSource[rowIndex] = {
      ...updatedDataSource[rowIndex],
      [`${header}_checked`]: isChecked,
      [`${header}_item`]: {...item, attributeValueLinkedToSKU: isChecked},
    };
    setTableDataSource(updatedDataSource);
    const req: LikedSkuModel = {
      akiItemNo: sessionStorage.getItem('itemNumber') || '',
      akiAttributeName: item.attributeName,
      akiAttributeValue: item.attributeValue,
      akiLink: isChecked,
    };
    if (!req.akiItemNo) {
      extractUserMessage('Item Number not found in session storage.');
      return;
    }
    try {
      const response: ApiResponse<LikedSkuModel> = await addUpdateSKULinkedAttribute(req);
      if (response.isSuccess) {
        notify.success('Attribute Link Updated Successfully!');
      } else {
        extractUserMessage('Failed to update attribute link.');
        const revertedDataSource = [...tableDataSource];
        revertedDataSource[rowIndex] = {
          ...revertedDataSource[rowIndex],
          [`${header}_checked`]: !isChecked,
          [`${header}_item`]: {...item, attributeValueLinkedToSKU: !isChecked},
        };
        setTableDataSource(revertedDataSource);
      }
    } catch (error) {
      console.error('Error updating linked attribute:', error);
      extractUserMessage('Something went wrong updating link.');
      const revertedDataSource = [...tableDataSource];
      revertedDataSource[rowIndex] = {
        ...revertedDataSource[rowIndex],
        [`${header}_checked`]: !isChecked,
        [`${header}_item`]: {...item, attributeValueLinkedToSKU: !isChecked},
      };
      setTableDataSource(revertedDataSource);
    }
  };

  const columns: TableProps<TableRowData>['columns'] = attributeNames.flatMap((header) => [
    {
      title: header,
      dataIndex: `${header}_value`,
      key: `${header}_value`,
      render: (text: string | null) => text ?? '',
    },
    {
      title: 'Select',
      dataIndex: `${header}_checked`,
      key: `${header}_checked`,
      width: 80,
      align: 'center',
      render: (checked: boolean, record: TableRowData, rowIndex: number) => {
        const hasValue = record[`${header}_value`] !== null;
        return hasValue ? <Checkbox checked={checked} onChange={(e) => handleCheckboxChange(e, rowIndex, header)} /> : null;
      },
    },
  ]);

  return (
    <div className="main-container">
      <Spin spinning={loading}>
        <div className="flex flex-wrap justify-between items-center p-4 pb-1">
          <span className="text-sm font-medium">Attribute Multi Upload Form</span>
          <div className="flex gap-x-3">
            <Button type="default" onClick={handleCancel}>
              Close
            </Button>
            <Link to="/attributes/add">
              <Button type="primary">New Value</Button>
            </Link>
          </div>
        </div>
        <hr className="mt-2 mb-1 border-gray-200" />

        <div className="p-4">
          <Table columns={columns} dataSource={tableDataSource} rowKey="key" size="small" bordered pagination={false} className="attribute-multi-upload-table" />
        </div>
      </Spin>
    </div>
  );
};

export default AttributeMultiUpload;
