// CousinPCMS.Angular/src/app/components/home/category-attribute/category-attribute.component.ts
import { Component, Input, OnInit, SimpleChanges } from '@angular/core';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzFormModule } from 'ng-zorro-antd/form';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { NzTableModule } from 'ng-zorro-antd/table';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { AttributeModel, AttributeSetModel } from '../../../shared/models/attributeModel';
import { HomeService } from '../home.service';
import { error } from 'jquery';
import { DataService } from '../../../shared/services/data.service';
import { CategoryService } from '../../category/category.service';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { Subscription } from 'rxjs/internal/Subscription';
import { NzListModule } from 'ng-zorro-antd/list';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzPopconfirmModule } from 'ng-zorro-antd/popconfirm';

@Component({
  selector: 'cousins-category-attribute',
  imports: [NzButtonModule, NzInputModule, NzFormModule, ReactiveFormsModule, FormsModule, CommonModule,
    NzTableModule,
    NzCheckboxModule,
    NzSpinModule,
    NzIconModule,
    NzListModule,
    NzModalModule,
    NzSelectModule,
    NzPopconfirmModule
  ],
  templateUrl: './category-attribute.component.html',
  styleUrl: './category-attribute.component.css'
})
export class CategoryAttributeComponent implements OnInit {
  addAttributeSetsForm: FormGroup;
  attributeList: AttributeModel[] = [];
  isAttributeloading: boolean = false;
  isAttributeSetloading: boolean = false
  isloading: boolean = false;
  categoryDetails: any;
  categoryAttriIsVisible: boolean = false;
  currentAttributeSetName: string = '';
  @Input() categoryData: any = {};

  searchValue: string = '';
  lstAllAttributeSets: AttributeSetModel[] = [];
  isEditable:boolean=false;
  filteredData: AttributeModel[] = [];
  currentRowIndex!:number;
  constructor(private fb: FormBuilder,
    private homeService: HomeService,
    private dataService: DataService,
  ) {
    this.addAttributeSetsForm = this.fb.group({
      attributeSetName: ['', Validators.required],
      categoryID: [{ value: '', disabled: true }],
      attributeName: ['', Validators.required],
      attributeRequired: [true],
      notImportant: [true],
      listPosition: [0],
    })
  }
  ngOnChanges(changes: SimpleChanges) {
    if (changes['categoryData'] && this.categoryData) {
  
      if (this.categoryData && this.categoryData.origin) {
        const attributeSetName = `Attribute Set For - ${this.categoryData.origin.title}`;
        this.currentAttributeSetName = attributeSetName;

        this.addAttributeSetsForm.get('attributeSetName')?.setValue(`Attribute Set For - ${this.categoryData.origin.title}`);
        this.addAttributeSetsForm.get('categoryID')?.setValue(this.categoryData.origin.key);
        this.getAttributeSetsByAttributeSetName(attributeSetName);

      } else {
        const setName = this.categoryData.attributeSetName;
        this.currentAttributeSetName = setName;

        this.addAttributeSetsForm.get('attributeSetName')?.disable();
        this.addAttributeSetsForm.get('attributeSetName')?.setValue(`${this.categoryData.attributeSetName}`);
        this.addAttributeSetsForm.get('categoryID')?.setValue(this.categoryData.akiCategoryID);
        this.getAttributeSetsByAttributeSetName(setName);
      }

    }
  }

  ngOnInit(): void {

  }

  // get All Attributes data
  getAllAttributes() {
    this.isAttributeloading = true;
    this.homeService.getAllAttributes().subscribe({
      next: (response: any) => {
        if (response.isSuccess) {
          this.attributeList = response.value;
          if (this.lstAllAttributeSets && this.lstAllAttributeSets.length > 0) {
            const existingIds = this.lstAllAttributeSets.map((attribute: any) => attribute.attributeName);
            this.attributeList = this.attributeList.filter((attributeSets: any) => !existingIds.includes(attributeSets.attributeName));
          }
          this.filteredData = [...this.attributeList];          
          this.isAttributeloading = false;
        } else {
          this.dataService.ShowNotification('error', '', 'Failed To Load Data')
          this.isAttributeloading = false;
        }
        this.isAttributeloading = false;
      }
    })
  }

  addAttributeData(data: any) {
    this.isEditable=false;
    this.categoryAttriIsVisible = true;
    const existingName = this.addAttributeSetsForm.get('attributeSetName')?.value || '';
    const maxListOrder = this.lstAllAttributeSets && this.lstAllAttributeSets.length > 0
      ? Math.max(...this.lstAllAttributeSets.map((attribute: any) => Number(attribute.listPosition) || 0))
      : 0;

    const nextListPosition = maxListOrder + 1;

    if (!data || !data.attributeName) {
      this.dataService.ShowNotification('error', '', 'Attribute name is missing.');
      return;
    }
    this.addAttributeSetsForm.patchValue({
      attributeSetName: existingName.trim(),
      categoryID: this.addAttributeSetsForm.get('categoryID')?.value,
      attributeName: data.attributeName.trim(),
      attributeRequired: true,
      notImportant: true,
      listPosition: nextListPosition,
    });

  }

  deleteAttributeSets(item: any) {
    this.homeService.deleteAttributeSets(item.attributeName, item.attributeSetName).subscribe({
      next: (response: any) => {
        if (response.isSuccess) {
          this.dataService.ShowNotification('success', '', 'AttributeSets deleted successsully');
          this.getAttributeSetsByAttributeSetName(this.currentAttributeSetName);
          this.homeService.triggerReloadAttributes(); 
        } else {
          this.dataService.ShowNotification('error', '', 'AttributeSets not deleted successsully');
        }
      },
    })
  }
  getFormData() {
    return this.addAttributeSetsForm.getRawValue();
  }

  saveAttributeSets(): void {
    const attributeForm = this.addAttributeSetsForm.getRawValue();

    if (this.addAttributeSetsForm.valid) {
      this.homeService.addAttributeSets(attributeForm).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'Attribute added successfully');
            this.categoryAttriIsVisible = false
            const newAttributeSetName=this.addAttributeSetsForm.get('attributeSetName')?.value
            this.getAttributeSetsByAttributeSetName(newAttributeSetName);
            this.homeService.triggerReloadAttributes(); 
          } else {
            this.dataService.ShowNotification('error', '', 'Attribute not added successfully');
          }
        }
      })
    } else {
      Object.values(this.addAttributeSetsForm.controls).forEach((control) => {
        if (control.invalid) {
          control.markAsDirty();
          control.updateValueAndValidity({ onlySelf: true });
        }
      });
    }
  }

  btnCancel(): void {
    this.categoryAttriIsVisible = false;
  }
  handleOk(): void {
    this.categoryAttriIsVisible = false;
  }
  btnCancel2(): void {
    this.categoryAttriIsVisible = false;
  }
  getAttributeSetsByAttributeSetName(attributeSetName: string) {
    const encodedAttributeSetName = encodeURIComponent(attributeSetName);
    this.isAttributeSetloading = true;
    this.homeService.getAttributeSetsByAttributeSetName(encodedAttributeSetName).subscribe({
      next: (response: any) => {
        if (response.isSuccess) {
          this.lstAllAttributeSets = response.value.sort((a: any, b: any) => a.listPosition - b.listPosition);
          this.isAttributeSetloading = false;
          this.getAllAttributes();
        } else {
          this.dataService.ShowNotification('error', '', 'Failed to load attribute sets');
          this.isAttributeSetloading = false;
        }
      }, error: () => {
        this.isAttributeSetloading = false;
        this.dataService.ShowNotification('error', '', 'Failed to load attribute sets');
      }
    })
  }
 
  editAtrributeSets(row: any,index:number) {
    this.isEditable=true;
    this.currentRowIndex=index;  
    this.categoryAttriIsVisible = true;
    const existingName = this.addAttributeSetsForm.get('attributeSetName')?.value || '';

    if (!row || !row.attributeName) {
      this.dataService.ShowNotification('error', '', 'Attribute name is missing.');
      return;
    }
    this.addAttributeSetsForm.patchValue({
      attributeSetName: existingName.trim(),
      categoryID: this.addAttributeSetsForm.get('categoryID')?.value,
      attributeName: row.attributeName.trim(),
      attributeRequired: row.attributeRequired ,
      notImportant:  row.notImportant,
      listPosition: row.listPosition,
    });

  }
  updateAttributeSets(): void {
    this.isEditable=true;
    const listPosition = Number(this.addAttributeSetsForm.get('listPosition')?.value);

// Check if the listPosition already exists, but allow if it's the same row
    const isListPositionDuplicate = this.lstAllAttributeSets.some((attribute: any, idx: number) => {
      return idx !== this.currentRowIndex && Number(attribute.listPosition) === listPosition;
    });

    if (isListPositionDuplicate) {
      // this.dataService.ShowNotification('error', '', 'List position already exists, please choose another number');
      this.addAttributeSetsForm.get('listPosition')?.setErrors({ duplicate: true });
      return;
    }
    const attributeForm = this.addAttributeSetsForm.getRawValue();

    if (this.addAttributeSetsForm.valid) {
      this.homeService.updateAttributeSets(attributeForm).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'Attributesets updated successfully');
            this.categoryAttriIsVisible = false
            const newAttributeSetName=this.addAttributeSetsForm.get('attributeSetName')?.value
            this.getAttributeSetsByAttributeSetName(newAttributeSetName);
            this.homeService.triggerReloadAttributes(); 
          } else {
            this.dataService.ShowNotification('error', '', 'Attributesets not updated successfully');
          }
        }
      })
    } else {
      Object.values(this.addAttributeSetsForm.controls).forEach((control) => {
        if (control.invalid) {
          control.markAsDirty();
          control.updateValueAndValidity({ onlySelf: true });
        }
      });
    }
  }
   
  onSearch() {
    const searchText = this.searchValue?.toLowerCase().replace(/\s/g, '') || '';
  
    if (!searchText) {
      this.filteredData = [...this.attributeList];
      return;
    }
  
    this.filteredData = this.attributeList.filter(item => {
      const normalize = (str: string) => str?.toLowerCase().replace(/\s/g, '') || '';
      
      return  normalize(item.attributeName).includes(searchText)||
              normalize(item.attributeDescription).includes(searchText) || 
              normalize(item.searchType).includes(searchText)
    }); 
  }
  
  clearSearchText(): void {
    this.searchValue = '';
    this.filteredData = [...this.attributeList];
  }
  sortField = '';
  sortOrder: any = null;
  sort(field: string): void {
    this.sortField = field;
    this.sortOrder = this.sortOrder === 'ascend' ? 'descend' : 'ascend';
    this.sortData();
  }
  sortData(): void {
    if (!this.sortField || !this.sortOrder) {
      this.lstAllAttributeSets = [...this.lstAllAttributeSets];
      return;
    }

    this.lstAllAttributeSets.sort((a, b) => {
      const isAsc = this.sortOrder === 'ascend';
      switch (this.sortField) {
        case 'attributeName':
          return this.compare(a.attributeName, b.attributeName, isAsc);
        case 'listPosition':
          return this.compare(a.listPosition, b.listPosition, isAsc);
        default:
          return 0;
      }
    });
    
  }

  compare(a: any, b: any, isAsc: boolean): number {
    return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
  }
}

<div class="p-1">
  <form nz-form [formGroup]="addAttributeSetsForm">
    <!-- Category Info -->
    <div class="grid grid-cols-12 gap-4 py-2">
      <!-- Attribute Set Name (takes more width) -->
      <nz-form-item class="col-span-12 sm:col-span-5">
        <nz-form-label [nzNoColon]="true">Attribute Set Name</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="attributeSetName" id="attributeSetName" />
        </nz-form-control>
      </nz-form-item>

      <!-- Category Id (smaller column) -->
      <nz-form-item class="col-span-12 sm:col-span-3">
        <nz-form-label [nzNoColon]="true">Category Id</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="categoryID" id="categoryId" />
        </nz-form-control>
      </nz-form-item>
    </div>
    <!-- model for categoryAttriIsVisible  -->
    <nz-modal [(nzVisible)]="categoryAttriIsVisible" nzTitle="Attribute Details" [nzFooter]="null" nzClosable="true"
      class="content-center" nzWidth="500px" (nzOnCancel)="btnCancel2()">
      <ng-container *nzModalContent>

        <div class="grid grid-cols-1 px-3 py-1 gap-2">
          <nz-form-item>
            <nz-form-label [nzNoColon]="true">Attribute Set Name</nz-form-label>
            <nz-form-control nzErrorTip="Attribute set name is required">
              <input nz-input formControlName="attributeSetName" class="w-full" type="text" />
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzNoColon]="true">Attribute Name</nz-form-label>
            <nz-form-control nzErrorTip="Attribute name is required">
              <input nz-input formControlName="attributeName" [readOnly]="true" class="w-full" type="text" />
            </nz-form-control>
          </nz-form-item>
          <nz-form-item class="flex gap-2">
            <nz-form-label [nzNoColon]="true">Attribute Required</nz-form-label>
            <label nz-checkbox formControlName="attributeRequired" nzValue="data.attributeRequired"></label>
            <nz-form-label [nzNoColon]="true">Not Important</nz-form-label>
            <label nz-checkbox formControlName="notImportant" nzValue="data.notImportant"></label>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzNoColon]="true">list Position</nz-form-label>
            <nz-form-control nzErrorTip="List position already exists, please choose another number">
              <input nz-input type="number" class="w-full" formControlName="listPosition">
            </nz-form-control>
          </nz-form-item>
        </div>

        <div class="px-3 mt-2 flex justify-end">
          <button nz-button nzType="primary"  *ngIf="!isEditable" (click)="saveAttributeSets()" class="text-white">Save</button>
          <button nz-button nzType="primary"  *ngIf="isEditable" (click)="updateAttributeSets()" class="text-white">update</button>
        </div>
      </ng-container>
    </nz-modal>
  </form>
  <!-- Attribute Grid -->
  <div class="grid grid-cols-6 gap-4 py-2">
    <div class="col-span-6 sm:col-span-4">
      <!-- Left Table -->
      <nz-table #attributelistTable [nzData]="lstAllAttributeSets" nzBordered="true" nzShowPagination="false"
        nzSize="small" [nzLoading]="isAttributeSetloading" [nzScroll]="{x:'600px',y: '300px'}">
        <thead>
          <tr>
            <th [nzWidth]="'200px'" (click)="sort('attributeName')" nzShowSort>Attribute Name</th>
            <th [nzWidth]="'40px'" >Required</th>
            <!-- <th [nzWidth]="'50px'">Not Important</th> -->
            <th [nzWidth]="'50px'"(click)="sort('listPosition')" nzShowSort>List Position</th>
            <th [nzWidth]="'35px'">Action</th>
          </tr>
        </thead>
        <tbody>
          @for (data of attributelistTable.data; track $index) {
          <tr>
            <td>{{ data.attributeName }}</td>
            <td><label nz-checkbox [(ngModel)]="data.attributeRequired" [disabled]="true"></label></td>
            <!-- <td><label nz-checkbox [(ngModel)]="data.notImportant" [disabled]="true"></label></td> -->
            <td>{{ data.listPosition }}</td>
            <td>
             <span class="flex gap-x-2"> <a (click)="editAtrributeSets(data,$index )">
                <nz-icon nzType="edit" nzTheme="outline" class="text-primary-theme w-5 h-4" >Edit</nz-icon>
              </a>
              <a (click)="deleteAttributeSets(data)">
                <nz-icon nzType="delete" class="text-danger w-5 h-4" nzTheme="outline">Unlink</nz-icon>                  
              </a>
            </span>
            </td>
          </tr>
          }
        </tbody>
      </nz-table>

      <!-- Right Scroll List -->
    </div>
    <div class="col-span-6 sm:col-span-2">
      <nz-spin [nzSpinning]="isAttributeloading">
        <ng-container *ngIf="(filteredData?.length ?? 0) > 0; else emptyList">
          <div class="h-70 overflow-y-scroll border border-light-border rounded-md bg-white">
            <nz-list nzSize="small">
              <nz-list-header
                class="text-sm flex justify-between gap-2 px-2 font-medium text-primary-font sticky top-0 bg-white z-10 border-b border-light-border">Attribute
                Details              
                <nz-form-item>      
                  <nz-form-control>
                    <nz-input-group [nzSuffix]="inputClearTpl" >
                      <input nz-input type="text" class="rounded" [(ngModel)]="searchValue" (input)="onSearch()" #searchBox />
                    </nz-input-group>
                  </nz-form-control>
                </nz-form-item>
            
                <ng-template #inputClearTpl>
                  @if (searchValue) {
                    <span aria-hidden="true" nz-icon nzTheme="fill" class="cursor-pointer" nzType="close-circle" (click)="clearSearchText()"></span>
                  } @else {
                    <nz-icon nzType="search" />
                  }
                </ng-template></nz-list-header>
              @for (item of filteredData; track $index) {
              <nz-list-item class="cursor-pointer text-secondary-font flex">
                <span>{{ item.attributeName }}</span>
                <a (click)="addAttributeData(item)">
                  <a (click)="addAttributeData(item)">Link</a>
                </a>
              </nz-list-item>
              }
            </nz-list>
          </div>
        </ng-container>

        <ng-template #emptyList>
          <div class="h-70 border border-light-border rounded-md bg-white text-gray-500  flex flex-col">
            <div class="text-sm font-medium flex justify-between px-2 py-2 border-b border-light-border text-primary-font">Attribute
              Details
              <nz-form-item>      
                <nz-form-control>
                  <nz-input-group [nzSuffix]="inputClearTpl" >
                    <input nz-input type="text" class="rounded" [(ngModel)]="searchValue" (input)="onSearch()" #searchBox />
                  </nz-input-group>
                </nz-form-control>
              </nz-form-item>
          
              <ng-template #inputClearTpl>
                @if (searchValue) {
                  <span aria-hidden="true" nz-icon nzTheme="fill" class="cursor-pointer" nzType="close-circle" (click)="clearSearchText()"></span>
                } @else {
                  <nz-icon nzType="search" />
                }
              </ng-template>
            </div>
            <div class="flex-grow flex items-center justify-center">
              <span class="text-sm">No attributes found</span>
            </div>
          </div>
        </ng-template>
      </nz-spin>
    </div>

  </div>
</div>

// CousinPCMS.React/src/components/home/CategoryAttribute.tsx
import React, {useState, useEffect, useCallback} from 'react';
import {Modal, Form, Input, Checkbox, Button, Table, Spin} from 'antd';
import {getAllAttributes, getAttributeSetsByAttributeSetName, addAttributeSets, deleteAttributeSets, updateAttributeSets1} from '../../services/HomeService';
import {extractUserMessage, showNotification} from '../../services/DataService';
import {CloseCircleFilled, SearchOutlined} from '@ant-design/icons';
import type {AttributeModel, AttributeModelResponse, AttributeSetModel} from '../../models/attributeModel';
import {ApiResponse} from '../../models/generalModel';
import {useNotification} from '../../contexts.ts/NotificationProvider';

interface CategoryAttributeProps {
  categoryData: any;
  eventComplete?: (event: any) => void;
}

const CategoryAttribute: React.FC<CategoryAttributeProps> = ({categoryData, eventComplete}) => {
  const [form] = Form.useForm();
  const [attributeList, setAttributeList] = useState<AttributeModel[]>([]);
  const [lstAllAttributeSets, setLstAllAttributeSets] = useState<AttributeSetModel[]>([]);
  const [isAttributeloading, setIsAttributeloading] = useState(false);
  const [isAttributeSetloading, setIsAttributeSetloading] = useState(false);
  const [categoryAttriIsVisible, setCategoryAttriIsVisible] = useState(false);
  const [currentAttributeSetName, setCurrentAttributeSetName] = useState('');
  const [searchValue, setSearchValue] = useState('');
  const [filteredData, setFilteredData] = useState<AttributeModel[]>([]);
  const [isEditable, setIsEditable] = useState(false);
  const [currentRowIndex, setCurrentRowIndex] = useState<number>();

  const notify = useNotification();

  // Fetch attribute sets and attributes when categoryData changes
  useEffect(() => {
    if (categoryData) {
      let attributeSetName = '';
      let categoryID = '';
      if (categoryData.origin) {
        attributeSetName = `Attribute Set For - ${categoryData.origin.title}`;
        categoryID = categoryData.origin.key;
      } else {
        attributeSetName = categoryData.attributeSetName || '';
        categoryID = categoryData.akiCategoryID || '';
      }
      setCurrentAttributeSetName(attributeSetName);
      form.resetFields();
      setTimeout(() => {
        form.setFieldsValue({
          attributeSetName,
          categoryID,
        });
      }, 100);
      fetchAttributeSetsByAttributeSetName(encodeURIComponent(attributeSetName));
    }
  }, [categoryData]);

  // Fetch all attributes
  const fetchAllAttributes = useCallback(
    (attributeSets?: AttributeSetModel[]) => {
      setIsAttributeloading(true);
      getAllAttributes().then((response: AttributeModelResponse) => {
        if (response.isSuccess) {
          let filtered = response.value;
          const sets = attributeSets !== undefined ? attributeSets : lstAllAttributeSets;
          if (sets.length > 0) {
            const existingIds = sets.map((a) => a.attributeName);
            filtered = filtered.filter((a: any) => !existingIds.includes(a.attributeName));
          }
          console.log('Filtered attributes:', filtered); // Debug log
          setAttributeList(filtered);
          setFilteredData(filtered);
        } else {
          showNotification('error', 'Failed To Load Data');
        }
        setIsAttributeloading(false);
      });
    },
    [lstAllAttributeSets]
  );

  // Fetch attribute sets by name
  const fetchAttributeSetsByAttributeSetName = useCallback(
    (attributeSetName: string) => {
      setIsAttributeSetloading(true);
      getAttributeSetsByAttributeSetName(attributeSetName)
        .then((response: ApiResponse<AttributeSetModel[]>) => {
          if (response.isSuccess && Array.isArray(response.value)) {
            setLstAllAttributeSets(response.value);
            fetchAllAttributes(response.value); // Pass new data here
          } else {
            showNotification('error', 'Failed to load attribute sets');
            setLstAllAttributeSets([]);
            fetchAllAttributes([]);
          }
          setIsAttributeSetloading(false);
        })
        .catch((error) => {
          console.error('Error fetching attribute sets:', error); // Debug log
          setIsAttributeSetloading(false);
          setLstAllAttributeSets([]);
          fetchAllAttributes([]);
          showNotification('error', 'Failed to load attribute sets');
        });
    },
    [fetchAllAttributes]
  );

  // Add attribute data to form
  const addAttributeData = (data: AttributeModel) => {
    setCategoryAttriIsVisible(true);
    setIsEditable(false);
    if (!data || !data.attributeName) {
      showNotification('error', 'Attribute name is missing.');
      return;
    }
    const existingName = form.getFieldValue('attributeSetName')?.trim() || '';
    const categoryID = form.getFieldValue('categoryID') || '';
    const maxListOrder = lstAllAttributeSets.reduce((max, item) => Math.max(max, Number(item.listPosition) || 0), 0);
    const nextListPosition = maxListOrder + 1;
    form.setFieldsValue({
      attributeSetName: existingName,
      categoryID: categoryID,
      attributeName: data.attributeName.trim(),
      attributeRequired: true,
      notImportant: true,
      listPosition: nextListPosition,
    });
  };

  // Delete attribute set
  const handleDeleteAttributeSet = (item: AttributeSetModel) => {
    deleteAttributeSets(item.attributeName, item.attributeSetName).then((response: any) => {
      if (response.isSuccess) {
        showNotification('success', 'AttributeSets deleted successfully');
        fetchAttributeSetsByAttributeSetName(currentAttributeSetName);
      } else {
        showNotification('error', 'AttributeSets not deleted successfully');
      }
    });
  };

  // Save attribute set
  const saveAttributeSets = () => {
    form
      .validateFields()
      .then((values) => {
        addAttributeSets(values).then((response: ApiResponse<string>) => {
          if (response.isSuccess) {
            showNotification('success', 'Attribute added successfully');
            setCategoryAttriIsVisible(false);
            fetchAttributeSetsByAttributeSetName(values.attributeSetName);
            if (eventComplete) eventComplete('ok');
          } else {
            const raw = response?.value || 'Unknown error';
            const userMsg = extractUserMessage(raw);
            notify.error(userMsg);
            // showNotification('error', 'Attribute not added successfully');
          }
        });
      })
      .catch(() => {
        // Validation error
      });
  };

  // Cancel modal
  const handleCancel = () => {
    setCategoryAttriIsVisible(false);
    if (eventComplete) eventComplete('cancel');
  };

  // Edit attribute set
  const editAttributeSet = (row: AttributeSetModel, index: number) => {
    setCategoryAttriIsVisible(true);
    setCurrentRowIndex(index);
    setIsEditable(true);
    const existingName = form.getFieldValue('attributeSetName') || '';
    const maxListOrder = lstAllAttributeSets.length > 0 ? Math.max(...lstAllAttributeSets.map((a) => Number(a.listPosition) || 0)) : 0;
    const nextListPosition = maxListOrder + 1;
    if (!row || !row.attributeName) {
      showNotification('error', 'Attribute name is missing.');
      return;
    }
    form.setFieldsValue({
      attributeSetName: existingName.trim(),
      categoryID: form.getFieldValue('categoryID'),
      attributeName: row.attributeName.trim(),
      attributeRequired: true,
      notImportant: true,
      listPosition: nextListPosition,
    });
  };

  const updateAttributeSets = async () => {
    form
      .validateFields()
      .then((values) => {
        setIsEditable(true);
        const listPosition = Number(values.listPosition);

        const isListPositionDuplicate = lstAllAttributeSets.some((attribute, idx) => {
          return idx !== currentRowIndex && Number(attribute.listPosition) === listPosition;
        });

        if (isListPositionDuplicate) {
          // message.error('List position already exists, please choose another number');
          return;
        }

        updateAttributeSets1(values).then((response: ApiResponse<string>) => {
          if (response.isSuccess) {
            showNotification('success', 'Attribute added successfully');
            setCategoryAttriIsVisible(false);
            fetchAttributeSetsByAttributeSetName(values.attributeSetName);
            if (eventComplete) eventComplete('ok');
          } else {
            const raw = response?.value || 'Unknown error';
            const userMsg = extractUserMessage(raw);
            notify.error(userMsg);
            // showNotification('error', 'Attribute not added successfully');
          }
        });
      })
      .catch(() => {
        // Validation error
      });
  };

  // Table columns
  const columns = [
    {title: 'Attribute Name', dataIndex: 'attributeName', width: 200},
    {title: 'Required', dataIndex: 'attributeRequired', width: 40, render: (val: boolean) => <Checkbox checked={val} disabled />},
    {title: 'Not Important', dataIndex: 'notImportant', width: 50, render: (val: boolean) => <Checkbox checked={val} disabled />},
    {title: 'List Position', dataIndex: 'listPosition', width: 50},
    {
      title: 'Action',
      dataIndex: 'action',
      width: 35,
      render: (_: any, record: AttributeSetModel, index: number) => (
        <span className="flex gap-x-1">
          <a onClick={() => editAttributeSet(record, index)}>
            <span className="text-primary-theme"> Edit </span>
          </a>
          <a onClick={() => handleDeleteAttributeSet(record)}>
            <span className="text-danger"> Unlink </span>
          </a>
        </span>
      ),
    },
  ];

  const onSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setSearchValue(value);
    const searchText = value?.toLowerCase().replace(/\s/g, '') || '';
    if (!searchText) {
      setFilteredData([...attributeList]);
      return;
    }
    const filtered = attributeList.filter((item) => {
      const normalize = (str: string) => str?.toLowerCase().replace(/\s/g, '') || '';
      return normalize(item.attributeName).includes(searchText);
    });
    setFilteredData(filtered);
  };

  const clearSearchText = () => {
    setSearchValue('');
    setFilteredData([...attributeList]);
  };

  return (
    <div className="p-1">
      {/* Attribute Set Form */}
      <Form form={form} layout="vertical">
        <div className="grid grid-cols-12 gap-4 py-2">
          <div className="col-span-12 sm:col-span-5">
            <Form.Item label="Attribute Set Name" name="attributeSetName" rules={[{required: true, message: 'Required'}]}>
              <Input disabled value={form.getFieldValue('attributeSetName') || ''} />
            </Form.Item>
          </div>
          <div className="col-span-12 sm:col-span-3">
            <Form.Item label="Category Id" name="categoryID" rules={[{required: true, message: 'Required'}]}>
              <Input disabled value={form.getFieldValue('categoryID') || ''} />
            </Form.Item>
          </div>
        </div>
      </Form>
      {/* Attribute Set Modal */}
      <Modal open={categoryAttriIsVisible} title="Attribute Details" onCancel={handleCancel} footer={null} width={500} centered destroyOnClose>
        <Spin spinning={isAttributeSetloading}>
          <Form form={form} layout="vertical" className="p-2">
            <div className="grid grid-cols-1 gap-2 px-3 py-1">
              <Form.Item label="Attribute Set Name" name="attributeSetName" rules={[{required: true, message: 'Required'}]}>
                <Input disabled className="w-full" />
              </Form.Item>
              <Form.Item label="Attribute Name" name="attributeName" rules={[{required: true, message: 'Attribute name is required'}]}>
                <Input readOnly className="w-full" />
              </Form.Item>
              <div className="flex gap-2 items-center">
                <Form.Item name="attributeRequired" valuePropName="checked" noStyle>
                  <Checkbox>Attribute Required</Checkbox>
                </Form.Item>
                <Form.Item name="notImportant" valuePropName="checked" noStyle>
                  <Checkbox>Not Important</Checkbox>
                </Form.Item>
              </div>
              <Form.Item label="List Position" name="listPosition">
                <Input type="number" className="w-full" />
              </Form.Item>
            </div>
            <div className="flex justify-end px-3 mt-2">
              {isEditable ? (
                <Button type="primary" onClick={updateAttributeSets} className="text-white">
                  Update
                </Button>
              ) : (
                <Button type="primary" onClick={saveAttributeSets} className="text-white">
                  Save
                </Button>
              )}
            </div>
          </Form>
        </Spin>
      </Modal>
      {/* Attribute Grid */}
      <div className="grid grid-cols-6 gap-4 py-2">
        <div className="col-span-6 sm:col-span-4">
          <Table columns={columns} dataSource={lstAllAttributeSets} rowKey="attributeName" bordered size="small" loading={isAttributeSetloading} pagination={false} />
        </div>
        <div className="col-span-6 sm:col-span-2">
          <Spin spinning={isAttributeloading}>
            <div className="h-70 overflow-y-scroll border border-gray-200 rounded-md bg-white">
              <div className="text-sm font-medium text-center text-primary-font sticky top-0 bg-white z-10 border-b border-gray-200">Attribute Details</div>
              <div className="w-64 flex items-center">
                <Input
                  placeholder="Search"
                  value={searchValue}
                  onChange={onSearch}
                  suffix={searchValue ? <CloseCircleFilled className="cursor-pointer" onClick={clearSearchText} aria-hidden="true" /> : <SearchOutlined />}
                />
              </div>
              {filteredData.length > 0 ? (
                <div>
                  {filteredData.map((item, idx) => (
                    <div key={idx} className="flex justify-between items-center px-4 py-2 cursor-pointer text-secondary-font border-b border-gray-100">
                      <span>{item.attributeName}</span>
                      <a onClick={() => addAttributeData(item)} className="text-primary-theme">
                        Link
                      </a>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="flex-grow flex items-center justify-center">
                  <span className="text-sm">No attributes found</span>
                </div>
              )}
            </div>
          </Spin>
        </div>
      </div>
    </div>
  );
};

export default CategoryAttribute;
