// CousinPCMS.Angular/src/app/components/home/product-display/product-display.component.ts
import { Component, EventEmitter, Input, Output, SimpleChanges, ViewChild } from '@angular/core';
import { HomeService } from '../home.service';
import { CommonModule } from '@angular/common';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { Product, ProductResponse } from '../../../shared/models/productModel';
import { DataService } from '../../../shared/services/data.service';
import { NzToolTipModule } from 'ng-zorro-antd/tooltip';
import { CategoryAttributeComponent } from '../category-attribute/category-attribute.component';
import { NzModalModule, NzModalService } from 'ng-zorro-antd/modal';
import { forkJoin } from 'rxjs';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { FormsModule } from '@angular/forms';
import { NzInputModule } from 'ng-zorro-antd/input';
import { ProductComponent } from "../../product/product.component";
import { ProductDetailsComponent } from '../../product/product-details/product-details.component';

@Component({
  selector: 'cousins-product-display',
  imports: [CommonModule, NzSpinModule, NzToolTipModule, NzModalModule, CategoryAttributeComponent, NzFormModule, NzIconModule, FormsModule, NzInputModule, ProductComponent],
  templateUrl: './product-display.component.html',
  styleUrl: './product-display.component.css'
})
export class ProductDisplayComponent {
  @ViewChild(ProductDetailsComponent) productComponent!: ProductDetailsComponent;

  @Input() selectedCategory: string = '';
  @Output() productSelected = new EventEmitter<number>();
  selectedProduct?: number;
  products: Product[] = [];
  displayText: string = 'Click a category to view the product';
  loading: boolean = false;
  categoryAttriIsVisible: boolean = false;
  categoryProductVisible: boolean = false;
  categoryData: any = {};
  lstAllAttributeSets: any[] = [];

  allProductAtrributes: any[] = [];
  searchValue: string = '';
  filteredData: any[] = [];

  constructor(private homeService: HomeService, private dataService: DataService) { }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['selectedCategory']) {
      // this.selectedProduct = 0;
      if (sessionStorage.getItem('categoryId')) {
        const productIdStr = sessionStorage.getItem('productId');
        const productId: number | undefined = productIdStr ? +productIdStr : undefined;
        this.selectedProduct = productId;
        this.getDataInParallel()
      } else {
        this.products = [];
        this.displayText = 'Click a category to view the product';
      }
      this.homeService.reloadAttributes$.subscribe(() => {
        this.getDataInParallel();
      });
    }
  }

  onProductClick(data: Product) {
    if (!data) return; // Prevents undefined errors
    this.selectedProduct = data.akiProductID;
    sessionStorage.setItem('productId', data.akiProductID.toString());
    sessionStorage.removeItem('itemNumber');
    this.productSelected.emit(data.akiProductID);
    
  }
  onProductRightClick(product: any): void {
    this.selectedProduct = product?.akiProductID;
    this.categoryData = product;
    this.categoryAttriIsVisible = true; // Opens the modal
  }

  handleOk(val: string) {
    this.categoryAttriIsVisible = false;
    this.categoryProductVisible = false;
    if(val !== 'cancel') {
      this.getDataInParallel();
    }
  }

  handleCancel() {
    this.categoryAttriIsVisible = false;
  }

  getDataInParallel(): void {
    // this.loading = true;
    this.products = [];
    this.lstAllAttributeSets = [];
    if (!this.selectedCategory) return;
    forkJoin({
      productList: this.homeService.getProductListByCategoryId(this.selectedCategory),
      attributeList: this.homeService.getDistinctAttributeSetsByCategoryId(this.selectedCategory)
    }).subscribe({
      next: ({ productList, attributeList }) => {
        if (productList.isSuccess) {
          if (productList.value && productList.value.length > 0) {
            this.products = productList.value.filter((res: Product) => res?.akiProductIsActive);
            if (this.products && this.products.length > 0) {
              this.displayText = '';
              this.productSelected.emit(this.selectedProduct);
            } else {
              this.displayText = 'No Product Found';
            }
          } else {
            this.displayText = 'No Product Found';
          }
        }
        if (attributeList.isSuccess) {
          this.lstAllAttributeSets = attributeList.value;
          this.allProductAtrributes = [
            ...(Array.isArray(this.products) ? this.products : []),
            ...(Array.isArray(this.lstAllAttributeSets) ? this.lstAllAttributeSets : [])
          ];
          this.filteredData = [...this.allProductAtrributes];
        } else {
          this.dataService.ShowNotification('error', '', 'Failed to load attribute sets')
        }
        this.loading = false;
      },
      error: (error) => {
        console.error('Error in API calls', error);
        this.loading = false;
      }
    });
  }

  onSearch() {
    const searchText = this.searchValue?.toLowerCase().replace(/\s/g, '') || '';
  
    if (!searchText) {
      this.filteredData = [...this.allProductAtrributes];
      return;
    }
  
    this.filteredData = this.allProductAtrributes.filter(item => {
      const normalize = (str: string) => str?.toLowerCase().replace(/\s/g, '') || '';
      
      return  normalize(item.akiProductName).includes(searchText) || 
              normalize(item.attributeSetName).includes(searchText)
    }); 
    if (this.filteredData.length === 0) {
      this.displayText = 'No Data';
    }
  }
  
  clearSearchText(): void {
    this.searchValue = '';
    this.filteredData = [...this.allProductAtrributes];
  }

  editProduct(){
    if (!this.selectedProduct) {
      this.dataService.ShowNotification('error','','Please select product name.')
      return;
    }  
    this.categoryProductVisible = true;
  }
  
  addProduct(){ 
    // sessionStorage.removeItem('productId');
    if (this.productComponent) {
      this.productComponent.productForm.reset();
    }
    this.categoryProductVisible = true;
  }

}
<div class="product-container">
  <div class="product-header flex justify-between gap-x-1 items-center">
 <!-- <div class="flex justify-between gap-1 me-1"> -->
    <span>Products and Attribute Sets</span>   
    <a (click)="addProduct()">Add</a>
    <a (click)="editProduct()">Edit</a>
 <!-- </div>  -->
    <nz-form-item>
      <nz-form-control>
        <nz-input-group [nzSuffix]="inputClearTpl">
          <input nz-input type="text" class="rounded" [(ngModel)]="searchValue" (input)="onSearch()" #searchBox placeholder="Search" />
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <ng-template #inputClearTpl>
      @if (searchValue) {
      <span aria-hidden="true" nz-icon nzTheme="fill" class="cursor-pointer" nzType="close-circle" (click)="clearSearchText()"></span>
      }@else{
      <nz-icon nzType="search" />
      }
    </ng-template>
  </div>

  <nz-spin [nzSpinning]="loading">
    <!-- Product List -->
    @if (filteredData && filteredData.length > 0) {
    <ul class="product-list divide-y divide-gray-200 leading-2">
      @for (product of filteredData; track $index) { @if (product) { @if (product && product.akiProductID) {
      <li class="product-item" (click)="onProductClick(product)" [ngClass]="{'bg-bg-light': selectedProduct == product?.akiProductID}">
        {{ product.akiProductName }}
      </li>
      } @if (product && product.attributeSetName) {
      <li class="product-item" (click)="onProductRightClick(product)" [ngClass]="{'bg-bg-light': selectedProduct == product?.akiCategoryID}">
        <span class="text-primary-font"> {{ product.attributeSetName }}</span>
      </li>
      } } }
    </ul>
    } @else {
    <div class="empty-message h-48">
      {{ displayText }}
    </div>
    }
  </nz-spin>
</div>

<!-- Category-attributes -->
<div>
  <nz-modal [(nzVisible)]="categoryAttriIsVisible" nzTitle="Attribute set form" [nzFooter]="null" nzClosable="true" class="content-center" nzWidth="1100px" (nzOnCancel)="handleCancel()">
    <ng-container *nzModalContent>
      <cousins-category-attribute [categoryData]="categoryData"></cousins-category-attribute>
    </ng-container>
  </nz-modal>
</div>

<!-- Category-Product -->
<div>
  <nz-modal [(nzVisible)]="categoryProductVisible" [nzFooter]="null" nzClosable="false" [nzClassName]="'no-padding-modal'" nzWidth="1500px">
    <ng-container *nzModalContent>
      <cousins-product (eventComplete)="handleOk($event)" [isSetAttributslist]="isSetAttributslist" ></cousins-product>
    </ng-container>
  </nz-modal>
</div>

// CousinPCMS.React/src/components/home/ProductDisplay.tsx
import React, {useState, useEffect, useCallback} from 'react';
import {Spin, Modal, Input} from 'antd';
import {SearchOutlined, CloseCircleFilled} from '@ant-design/icons';

import {Product} from '../../models/productModel';
import {AttributeSetModel} from '../../models/attributeModel';
import {getDistinctAttributeSetsByCategoryId, getProductListByCategoryId} from '../../services/HomeService';
import CategoryAttribute from './CategoryAttribute';
import {useNavigate} from 'react-router';
import {useNotification} from '../../contexts.ts/useNotification';

interface ProductDisplayProps {
  selectedCategory: string;
  onProductSelected: (productId: number | undefined) => void;
}

function ProductDisplay({selectedCategory, onProductSelected}: ProductDisplayProps) {
  const [selectedProduct, setSelectedProduct] = useState<number | undefined>(undefined);
  const [products, setProducts] = useState<Product[]>([]);
  const [allProductAttributes, setAllProductAttributes] = useState<(Product | AttributeSetModel)[]>([]);
  const [filteredData, setFilteredData] = useState<(Product | AttributeSetModel)[]>([]);
  const [displayText, setDisplayText] = useState('Click a category to view the product');
  const [loading, setLoading] = useState(false);
  const [categoryAttriIsVisible, setCategoryAttriIsVisible] = useState(false);
  const [categoryData, setCategoryData] = useState({});
  const [searchValue, setSearchValue] = useState('');
  const notify = useNotification();
  const navigate = useNavigate();

  const fetchData = useCallback(async () => {
    if (!selectedCategory) {
      setProducts([]);
      setAllProductAttributes([]);
      setFilteredData([]);
      onProductSelected(undefined);
      setDisplayText('Click a category to view the product');
      return;
    }

    setLoading(true);
    setDisplayText('');

    try {
      const [productListResponse, attributeListResponse] = await Promise.all([getProductListByCategoryId(selectedCategory), getDistinctAttributeSetsByCategoryId(selectedCategory)]);

      let currentProducts: Product[] = [];
      if (productListResponse.isSuccess && productListResponse.value) {
        currentProducts = productListResponse.value.filter((p: Product) => p?.akiProductIsActive);
        setProducts(currentProducts);
      } else {
        setProducts([]);
      }

      let currentAttributeSets: AttributeSetModel[] = [];
      if (attributeListResponse.isSuccess && attributeListResponse.value) {
        currentAttributeSets = attributeListResponse.value;
      }

      const combinedData: (Product | AttributeSetModel)[] = [...(Array.isArray(currentProducts) ? currentProducts : []), ...(Array.isArray(currentAttributeSets) ? currentAttributeSets : [])];
      setAllProductAttributes(combinedData);

      const currentSearchValue = searchValue?.toLowerCase().replace(/\s/g, '') || '';
      if (currentSearchValue) {
        const filtered = combinedData.filter((item) => {
          const normalize = (str: string | undefined) => str?.toLowerCase().replace(/\s/g, '') || '';
          return (
            ('akiProductName' in item && normalize(item.akiProductName).includes(currentSearchValue)) || ('attributeSetName' in item && normalize(item.attributeSetName).includes(currentSearchValue))
          );
        });
        setFilteredData(filtered);
        if (filtered.length === 0) setDisplayText('No Data');
      } else {
        setFilteredData(combinedData);
        if (combinedData.length === 0) setDisplayText('No Product or Attribute Sets Found');
        else setDisplayText('');
      }

      const persistedProductId = sessionStorage.getItem('productId');
      if (persistedProductId) {
        const numProductId = Number(persistedProductId);

        if (currentProducts.some((p) => p.akiProductID === numProductId)) {
          setSelectedProduct(numProductId);
        } else {
          sessionStorage.removeItem('productId');
          setSelectedProduct(undefined);
        }
      } else {
        setSelectedProduct(undefined);
      }
    } catch (error) {
      console.error('Error fetching data:', error);
      notify.error('Failed to load data');
      setDisplayText('Error loading data');
      setProducts([]);
      setAllProductAttributes([]);
      setFilteredData([]);
    } finally {
      setLoading(false);
    }
  }, [selectedCategory, searchValue, notify, onProductSelected]);

  useEffect(() => {
    fetchData();

    if (selectedCategory) {
      sessionStorage.setItem('CategoryId', selectedCategory);
    } else {
      setProducts([]);
      setDisplayText('Click a category to view the product');
    }
  }, [selectedCategory, fetchData]);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setSearchValue(value);

    const searchText = value?.toLowerCase().replace(/\s/g, '') || '';

    if (!searchText) {
      setFilteredData([...allProductAttributes]);
      if (allProductAttributes.length === 0 && selectedCategory) setDisplayText('No Product or Attribute Sets Found');
      else if (!selectedCategory) setDisplayText('Click a category to view the product');
      else setDisplayText('');
      return;
    }

    const filtered = allProductAttributes.filter((item) => {
      const normalize = (str: string | undefined) => str?.toLowerCase().replace(/\s/g, '') || '';
      return ('akiProductName' in item && normalize(item.akiProductName).includes(searchText)) || ('attributeSetName' in item && normalize(item.attributeSetName).includes(searchText));
    });

    setFilteredData(filtered);
    setDisplayText(filtered.length === 0 ? 'No Data Found Matching Search' : '');
  };

  const clearSearchText = () => {
    setSearchValue('');
    setFilteredData([...allProductAttributes]);
    if (allProductAttributes.length === 0 && selectedCategory) setDisplayText('No Product or Attribute Sets Found');
    else if (!selectedCategory) setDisplayText('Click a category to view the product');
    else setDisplayText('');
  };

  const handleProductClick = (product: Product) => {
    if (!product || !product.akiProductID) return;
    setSelectedProduct(product.akiProductID);
    sessionStorage.setItem('productId', product.akiProductID.toString());
    sessionStorage.removeItem('itemNumber');
    onProductSelected(product.akiProductID);
  };

  const handleAttributeSetClick = (attributeSet: AttributeSetModel) => {
    if (!attributeSet || !attributeSet.akiCategoryID) return;
    setSelectedProduct(attributeSet.akiCategoryID);
    setCategoryData(attributeSet);
    sessionStorage.removeItem('productId');
    onProductSelected(undefined);
    setCategoryAttriIsVisible(true);
  };

  const handleEditProduct = () => {
    const productToEdit = products.find((p) => p.akiProductID === selectedProduct);
    if (!productToEdit) {
      notify.error('Please select a product name from the list to edit.');
      return;
    }

    navigate('/products/edit');
    setCategoryData(productToEdit);
  };

  const handleAddProduct = () => {
    navigate('/products/add');
  };

  const handleAttributeModalCancel = () => {
    setCategoryAttriIsVisible(false);
  };

  const inputSuffix = searchValue ? <CloseCircleFilled className="cursor-pointer" onClick={clearSearchText} aria-hidden="true" /> : <SearchOutlined />;

  return (
    <div className="border border-border rounded-[5px] w-full bg-white overflow-hidden">
      <div className="bg-[#E2E8F0] text-primary-font text-[11px] font-semibold px-4 py-[5px] border-b border-border flex justify-between items-center">
        <div className="flex gap-2 items-center">
          <span>Products & Attribute Sets</span>
          <button className="text-primary-theme hover:underline text-xs" onClick={handleAddProduct}>
            Add
          </button>
          <button className={`text-primary-theme hover:underline text-xs me-1 ${!selectedProduct ? 'opacity-50 cursor-not-allowed' : ''}`} onClick={handleEditProduct} disabled={!selectedProduct}>
            Edit
          </button>
        </div>
        <div className="w-40">
          <Input placeholder="Search" value={searchValue} onChange={handleSearchChange} suffix={inputSuffix} className="rounded" />
        </div>
      </div>

      <Spin spinning={loading}>
        <div className="flex flex-col justify-center items-center bg-white min-h-[48px]">
          {filteredData && filteredData.length > 0 ? (
            <ul className="divide-y divide-border p-0 m-0 overflow-y-auto max-h-[700px] lg:max-h-[700px] md:max-h-[50vh] sm:max-h-[40vh] w-full">
              {filteredData.map((item: Product | AttributeSetModel) => {
                if ('akiProductID' in item) {
                  const isSelected = selectedProduct === item.akiProductID;
                  return (
                    <li
                      key={`prod-${item.akiProductID}`}
                      className={` px-4 py-1 cursor-pointer text-[10px]  transition-colors duration-300 ${isSelected ? 'bg-primary-theme-active' : 'hover:bg-gray-100  text-secondary-font'}`}
                      onClick={() => handleProductClick(item)}
                    >
                      {item.akiProductName}
                    </li>
                  );
                } else if ('attributeSetName' in item) {
                  return (
                    <li
                      key={`attr-${item.akiCategoryID}`}
                      className=" px-4 py-1 cursor-pointer text-[10px] text-secondary-font transition-colors duration-300 hover:bg-gray-100"
                      onClick={() => handleAttributeSetClick(item)}
                    >
                      <span className="text-primary-theme italic">{item.attributeSetName}</span>
                    </li>
                  );
                }
                return null;
              })}
            </ul>
          ) : (
            <div className="flex items-center justify-center h-12 text-secondary-font text-[10px] text-center">{displayText}</div>
          )}
        </div>
      </Spin>

      <Modal title="Attribute Set Form" open={categoryAttriIsVisible} onCancel={handleAttributeModalCancel} footer={null} width={1100} destroyOnClose>
        {categoryData && <CategoryAttribute categoryData={categoryData} />}
      </Modal>
    </div>
  );
}

export default ProductDisplay;
