// CousinPCMS.React/src/pages/SKUs.tsx
import {useState, useEffect, useCallback} from 'react';
import {useNavigate} from 'react-router';
import {Tabs, Button, Spin} from 'antd';
import type {FormInstance} from 'antd/es/form';
import SKUDetails from '../components/skus/SKUDetails';
import RelatedSKUs from '../components/skus/RelatedSKUs';
import AttributeSKU from '../components/skus/AttributeSKU';
import {updateSkus, getSkuItemById} from '../services/SkusService';
import {useNotification} from '../contexts.ts/useNotification';
import type {SKuList, SkuRequestModel} from '../models/skusModel';
import type {ApiResponse} from '../models/generalModel';

const SKUs = () => {
  const [activeTab, setActiveTab] = useState<string>('1');
  const [loading, setLoading] = useState<boolean>(true);
  const [btnSaveLoading, setBtnSaveLoading] = useState<boolean>(false);
  const [skuData, setSkuData] = useState<SKuList | null>(null);
  const [skuDetailsFormInstance, setSkuDetailsFormInstance] = useState<FormInstance | null>(null);
  const navigate = useNavigate();
  const notify = useNotification();

  const handleFormInstanceReady = useCallback((form: FormInstance) => {
    setSkuDetailsFormInstance(form);
  }, []);

  const fetchSkuByItemNumber = useCallback(
    async (itemNum: string) => {
      setLoading(true);
      try {
        const response: ApiResponse<SKuList[]> = await getSkuItemById(itemNum);
        if (response.isSuccess && response.value && response.value.length > 0) {
          setSkuData(response.value[0]);
        } else {
          notify.error('Failed To Load SKU Data');
          setSkuData(null);
        }
      } catch (err: unknown) {
        console.error('Error fetching SKU:', err);
        if (err && typeof err === 'object' && 'error' in err && (err as {error?: {title?: string}}).error?.title) {
          notify.error((err as {error?: {title?: string}}).error?.title || '');
        } else {
          notify.error('Something went wrong while fetching SKU data.');
        }
        setSkuData(null);
      } finally {
        setLoading(false);
      }
    },
    [notify]
  );

  useEffect(() => {
    if (location.pathname === '/departments/add') {
      setLoading(false);
      return;
    }

    const itemNumFromSession = sessionStorage.getItem('itemNumber') || '';
    if (itemNumFromSession) {
      fetchSkuByItemNumber(itemNumFromSession);
    } else {
      notify.error('SKU Item Number not found. Please select an SKU.');
      setLoading(false);
    }
  }, [navigate, notify, fetchSkuByItemNumber]);

  const handleCancel = () => {
    navigate('/home');
  };

  const handleSave = async () => {
    if (!skuDetailsFormInstance) {
      notify.error('SKU details form is not ready.');
      return;
    }
    if (!skuData) {
      notify.error('SKU data is missing.');
      return;
    }
    try {
      const values = await skuDetailsFormInstance.validateFields();
      const formData = values;
      const cleanData = (obj: Record<string, unknown>): SkuRequestModel => {
        const cleaned: Record<string, unknown> = {...obj};
        if (skuData) {
          cleaned.akiSKUID = skuData.akiSKUID;
          cleaned.akiProductID = skuData.akiProductID;
        }
        return cleaned as unknown as SkuRequestModel;
      };
      const cleanedPayload = cleanData(formData);
      const isLayoutTemplateSet = !!cleanedPayload.akiLayoutTemplate;
      cleanedPayload.akiPrintLayoutTemp = isLayoutTemplateSet;
      setBtnSaveLoading(true);
      const response = await updateSkus(cleanedPayload);
      if (response.isSuccess) {
        notify.success('SKU Details Updated Successfully');
        navigate('/home');
      } else {
        notify.error('SKU Details Update Failed');
      }
    } catch (errorInfo: unknown) {
      if (
        errorInfo &&
        typeof errorInfo === 'object' &&
        'errorFields' in errorInfo &&
        Array.isArray((errorInfo as {errorFields?: unknown[]}).errorFields) &&
        ((errorInfo as {errorFields?: unknown[]}).errorFields?.length ?? 0) > 0
      ) {
        notify.error('Please fill in all required fields correctly.');
        setActiveTab('1');
      } else {
        notify.error('An unexpected error occurred during save.');
      }
    } finally {
      setBtnSaveLoading(false);
    }
  };

  const tabBarExtraContent = (
    <div className="flex gap-x-3 mb-2 mr-2">
      <Button onClick={handleCancel}>Close</Button>
      {activeTab === '1' && (
        <Button
          type="primary"
          loading={btnSaveLoading}
          onClick={handleSave}
          disabled={!skuData}
        >
          Save
        </Button>
      )}
    </div>
  );
  

  return (
    <>
      <Spin spinning={loading}>
        <div className="main-container">
          <div className="p-4 pb-1">
            <span className="text-sm font-medium">Sku Form</span>
            <Tabs
              activeKey={activeTab}
              onChange={setActiveTab}
              tabBarExtraContent={tabBarExtraContent}
              className="product-tabs"
              items={[
                {
                  label: 'Sku',
                  key: '1',
                  children: <SKUDetails skuData={skuData} onFormInstanceReady={handleFormInstanceReady} />,
                },
                {
                  label: 'Related Skus',
                  key: '2',
                  children: <RelatedSKUs skuData={skuData} />,
                },

                {
                  label: 'All Linked Attributes',
                  key: '3',
                  children: <AttributeSKU skuData={skuData} />,
                },
              ]}
            />
          </div>
        </div>
      </Spin>
    </>
  );
};

export default SKUs;

// CousinPCMS.Angular/src/app/components/skus/skus.component.ts
import {CommonModule} from '@angular/common';
import {Component, ViewChild} from '@angular/core';
import {Router} from '@angular/router';
import {NzButtonModule} from 'ng-zorro-antd/button';
import {NzTabsModule} from 'ng-zorro-antd/tabs';
import {SkuDetailsComponent} from './sku-details/sku-details.component';
import {Subscription} from 'rxjs';
import {HomeService} from '../home/home.service';
import {DataService} from '../../shared/services/data.service';
import {RelatedSkuComponent} from './related-sku/related-sku.component';
import {SkusService} from './skus.service';
import {AttributeSkuComponent} from './attribute-sku/attribute-sku.component';
import {SKuList, SkuRequestModel} from '../../shared/models/skusModel';
import { ApiResponse } from '../../shared/models/generalModel';
import { NzSpinModule } from 'ng-zorro-antd/spin';

@Component({
  selector: 'cousins-skus',
  imports: [
    NzTabsModule, // ✅ Import Tabs
    NzButtonModule,
    SkuDetailsComponent,
    RelatedSkuComponent,
    AttributeSkuComponent,
    NzSpinModule
  ],
  templateUrl: './skus.component.html',
  styleUrl: './skus.component.css',
})
export class SkusComponent {
  activeTab: number = 0; // Default tab
  deleteLoading: boolean = false;
  loading: boolean = true;
  btnSaveLoading: boolean = false;

  skuData!: SKuList;
  private skuSubscription!: Subscription;
  @ViewChild(SkuDetailsComponent) skusDetailsComp!: SkuDetailsComponent;

  constructor(private readonly router: Router, private homeService: HomeService, private dataService: DataService, private skuService: SkusService) {}

  ngOnInit(): void {
    this.getSkuByItemNumber();  
  }

  cancle() {
    this.router.navigate(['/home']);
  }

  getSkuByItemNumber() {
    const itemNumber = sessionStorage.getItem('itemNumber') || '';
    if (itemNumber) {
      this.loading = true;
      this.skuService.getSkuItemById(itemNumber).subscribe({
        next: (response: ApiResponse<SKuList[]>) => {
          if (response.isSuccess) {
            this.skuData = response.value[0];
          } else {
            this.dataService.ShowNotification('error', '', 'Failed To Load Data');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else {
      this.dataService.ShowNotification('error', '', 'Please select sku name from home page');
    }
  }

  delete() {
    const proData = this.skusDetailsComp.getFormData();
    this.deleteLoading = true;
    this.skuService.deleteSkus(proData.akiSKUID).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.dataService.ShowNotification('success', '', 'Skus Successfully Deleted');
          sessionStorage.removeItem('itemNumber');
          sessionStorage.removeItem('skuId');
          this.router.navigate(['/home']);
        } else {
          this.dataService.ShowNotification('error', '', 'Skus Details Failed Deleted');
        }
        this.deleteLoading = false;
      },
      error: (err) => {
        this.deleteLoading = false;
        if (err?.error) {
          this.dataService.ShowNotification('error', '', err.error.title);
        } else {
          this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      },
    });
  }

  saveDetails() {
    this.skusDetailsComp.skuForm.markAllAsTouched();

    if (!this.skusDetailsComp.skuForm.valid) {
      this.dataService.ShowNotification('error', '', 'Please fill in all required fields.');
      return;
    }

    // Get data from both components (if forms are valid)
    const skuData: SkuRequestModel = this.dataService.cleanEmptyNullToString(this.skusDetailsComp.getFormData());

    if (skuData.akiLayoutTemplate) {
      skuData.akiPrintLayoutTemp = true;
    }
    this.btnSaveLoading = true;
    this.skuService.updateSkus(skuData).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.dataService.ShowNotification('success', '', 'Sku Details Updated Successfully');
          this.router.navigate(['/home']);
        } else {
          this.dataService.ShowNotification('error', '', 'Sku Details Failed To Updated');
        }
        this.btnSaveLoading = false;
      },
      error: (err) => {
        this.btnSaveLoading = false;
        if (err?.error) {
          this.dataService.ShowNotification('error', '', err.error.title);
        } else {
          this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      },
    });
  }

  ngOnDestroy() {
    if (this.skuSubscription) {
      this.skuSubscription.unsubscribe();
    }
  }
}

<div class="bg-white rounded-lg m-5 pb-4">
    
    @if(activeTab === 0) {
      <label class="px-4 pt-3 mb-0 [color:var(--color-primary-font)] text-sm font-medium">Sku Form</label>
    } @else if (activeTab === 1) {
    <label class="px-4 pt-3 mb-0 [color:var(--color-primary-font)] text-sm font-medium">Related Skus</label>
    } @else {
    <label class="px-4 pt-3 mb-0 [color:var(--color-primary-font)] text-sm font-medium">All Linked Attributes</label>
    }
    
    <nz-spin [nzSpinning]="loading">
      <!-- Tabs -->
      <nz-tabset [(nzSelectedIndex)]="activeTab" [nzTabBarExtraContent]="extraTemplate">

        <nz-tab nzTitle="Sku">
          <cousins-sku-details [skuData]="skuData"></cousins-sku-details>
        </nz-tab>
    
        <nz-tab nzTitle="Related Skus">
        <cousins-related-sku  [skuData]="skuData"></cousins-related-sku>
        </nz-tab>

        <nz-tab nzTitle="All Linked Attributes">
          <cousins-attribute-sku ></cousins-attribute-sku>
        </nz-tab>
      </nz-tabset>


      <ng-template #extraTemplate >
        @if(activeTab === 0) {
          <div class="flex gap-x-3 mb-2">
              <button nz-button nzType="default" class="" (click)="cancle()">
                Cancel
              </button>
              <button nz-button nzType="default" class="" [nzLoading]="deleteLoading" (click)="delete()"
                nz-popconfirm
                [nzPopconfirmTitle]="'Are you sure you want to delete this Sku?'"
                (nzOnConfirm)="delete()"
                (nzOnCancel)="btnCancel()"
                [nzIcon]="iconTpl"
                nzPopconfirmPlacement="left">
                Delete
              </button>
              <button nz-button nzType="primary" class="text-white me-3"  [nzLoading]="btnSaveLoading" (click)="saveDetails()" >
                Save
              </button>
              <ng-template #iconTpl>
                <nz-icon nzType="question-circle-o" class="text-danger me-2"  />
            </ng-template>
          </div>
        }
      </ng-template>
    </nz-spin>
</div>
