// CousinPCMS.Angular/src/app/components/skus/attribute-sku/attribute-sku.component.ts
import {Component, Input, SimpleChanges} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {NzTableModule} from 'ng-zorro-antd/table';
import {SkusService} from '../skus.service';
import {DataService} from '../../../shared/services/data.service';
import {ApiResponse} from '../../../shared/models/generalModel';
import {NzIconModule} from 'ng-zorro-antd/icon';
import {NzInputModule} from 'ng-zorro-antd/input';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { LikedSkuModel } from '../../../shared/models/skusModel';

@Component({
  selector: 'cousins-attribute-sku',
  imports: [NzTableModule, FormsModule, NzIconModule, NzInputModule, NzFormModule,NzCheckboxModule],
  templateUrl: './attribute-sku.component.html',
  styleUrl: './attribute-sku.component.css',
})
export class AttributeSkuComponent {
  linkedAttributeList: any[] = [];
  searchValue: string = '';
  akiitemid!: number;
  loading: boolean = false;
  @Input() skuData!: any;
  linkedAttributeListFilter: any[] = [];

  constructor(private skusService: SkusService, private dataService: DataService) {}

  ngOnChanges(changes: SimpleChanges) {
    if (changes['skuData']) {
      if (this.skuData) {
        this.akiitemid = this.skuData.akiitemid;
        this.getSkuLinkedAttributes();
      }
    }
  }

  onSearch() {
    const searchText = this.searchValue?.toLowerCase().replace(/\s/g, '') || '';

    if (!searchText) {
      this.linkedAttributeListFilter = [...this.linkedAttributeList];
      return;
    }

    this.linkedAttributeListFilter = this.linkedAttributeList.filter((item) => {
      const normalize = (str: string) => str?.toLowerCase().replace(/\s/g, '') || '';

      return normalize(item.akiAttributeName).includes(searchText) || normalize(item.akiAttributeValue).includes(searchText);
    });
  }

  clearSearchText(): void {
    this.searchValue = '';
    this.linkedAttributeListFilter = [...this.linkedAttributeList];
  }

  getSkuLinkedAttributes() {
    this.skusService.getSkuLinkedAttributes(this.akiitemid).subscribe({
      next: (reponse: ApiResponse<LikedSkuModel[]>) => {
        if (reponse.isSuccess) {
          if (reponse.value && reponse.value.length > 0) {
            this.linkedAttributeList = reponse.value;
            this.linkedAttributeListFilter = [...this.linkedAttributeList];
          }
        } else {
          this.dataService.ShowNotification('error', '', reponse.exceptionInformation);
        }
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      },
    });
  }
}

<div class="px-4">
  <div class="grid grid-cols-1 md:grid-cols-5 mb-2">
    <nz-form-item>
      <nz-form-label [nzNoColon]="true">Search</nz-form-label>
      <nz-form-control>
        <nz-input-group [nzSuffix]="inputClearTpl">
          <input nz-input type="text" class="rounded" [(ngModel)]="searchValue" (input)="onSearch()" #searchBox />
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <ng-template #inputClearTpl>
      @if (searchValue) {
      <span aria-hidden="true" nz-icon nzTheme="fill" class="cursor-pointer" nzType="close-circle" (click)="clearSearchText()"></span>
      }@else{
      <nz-icon nzType="search" />
      }
    </ng-template>
  </div>

  <nz-table #headerTable [nzData]="linkedAttributeListFilter" nzSize="small" nzBordered [nzShowPagination]="false" [nzFrontPagination]="false" [nzScroll]="{y: '660px'}">
    <thead>
      <tr>
        <th nzWidth="80px"></th>
        <th>Attribute Name</th>
        <th>Attribute Value</th>
        <th nzWidth="100px">Link</th>
      </tr>
    </thead>
    <tbody>
      @for (data of headerTable.data; track $index) {
      <tr>
        <td></td>
        <td>{{ data.akiAttributeName }}</td>
        <td>{{ data.akiAttributeValue }}</td>
        <td><label nz-checkbox [(ngModel)]="data.akiLink" [disabled]="true"></label></td>
      </tr>
      }
    </tbody>
  </nz-table>
</div>

// CousinPCMS.React/src/components/skus/AttributeSKU.tsx
import React, {useState, useEffect, useMemo} from 'react';
import {Input, Table, Checkbox, Spin, Form} from 'antd';
import {SearchOutlined, CloseCircleFilled} from '@ant-design/icons';
import type {TableProps} from 'antd/es/table';

import {getSkuLinkedAttributes} from '../../services/SkusService';
import {useNotification} from '../../contexts.ts/useNotification';
import type {ApiResponse} from '../../models/generalModel';
import type {LikedSkuModel} from '../../models/skusModel';

interface AttributeSkuProps {
  skuData: {
    akiitemid: number | string | null | undefined;
  } | null;
}

interface LinkedAttributeItem extends LikedSkuModel {
  key: string;
}

const AttributeSKU: React.FC<AttributeSkuProps> = ({skuData}) => {
  const [loading, setLoading] = useState<boolean>(false);
  const [searchValue, setSearchValue] = useState<string>('');
  const [linkedAttributeList, setLinkedAttributeList] = useState<LinkedAttributeItem[]>([]);

  const notify = useNotification();
  const getSkuLinkedAttributesHandler = async (itemId: number | string) => {
    setLoading(true);
    setLinkedAttributeList([]);
    try {
      const response: ApiResponse<LikedSkuModel[]> = await getSkuLinkedAttributes(String(itemId));
      if (response.isSuccess && response.value) {
        const dataWithKeys = response.value.map((item, index) => ({
          ...item,
          key: `${item.akiAttributeName}-${item.akiAttributeValue}-${index}`,
        }));
        setLinkedAttributeList(dataWithKeys);
      } else {
        notify.info('No linked attributes found.');
      }
    } catch {
      notify.error('Failed to load linked attributes.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const itemNumber = skuData?.akiitemid;
    if (itemNumber) {
      getSkuLinkedAttributesHandler(itemNumber);
    }
  }, [skuData]);

  const filteredAttributeList = useMemo(() => {
    const normalizedSearch = searchValue?.toLowerCase().replace(/\s/g, '') || '';
    if (!normalizedSearch) {
      return linkedAttributeList;
    }

    const normalize = (str: string | undefined | null) => str?.toLowerCase().replace(/\s/g, '') || '';

    return linkedAttributeList.filter((item) => normalize(item.akiAttributeName).includes(normalizedSearch) || normalize(item.akiAttributeValue).includes(normalizedSearch));
  }, [searchValue, linkedAttributeList]);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchValue(e.target.value);
  };

  const clearSearchText = () => {
    setSearchValue('');
  };

  const columns: TableProps<LinkedAttributeItem>['columns'] = [
    {
      title: 'Attribute Name',
      dataIndex: 'akiAttributeName',
      ellipsis: true,
    },
    {
      title: 'Attribute Value',
      dataIndex: 'akiAttributeValue',
      ellipsis: true,
    },
    {
      title: 'Link',
      dataIndex: 'akiLink',
      width: 100,
      align: 'center',
      render: (isLinked) => <Checkbox checked={isLinked} disabled />,
    },
  ];

  return (
    <div className='px-4'>
      <Form layout="vertical" className="mb-4">
        <div className="grid grid-cols-1 md:grid-cols-5">
          <Form.Item label="Search" className="md:col-span-2 mb-0">
            <Input
              placeholder="Search by name or value..."
              value={searchValue}
              onChange={handleSearchChange}
              suffix={searchValue ? <CloseCircleFilled onClick={clearSearchText} style={{color: 'rgba(0,0,0,.45)', cursor: 'pointer'}} /> : <SearchOutlined style={{color: 'rgba(0,0,0,.45)'}} />}
            />
          </Form.Item>
        </div>
      </Form>

      <Spin spinning={loading}>
        <Table columns={columns} dataSource={filteredAttributeList} rowKey="key" size="small" bordered pagination={false} className="linked-attributes-table" />
      </Spin>
    </div>
  );
};

export default AttributeSKU;
