// CousinPCMS.Angular/src/app/components/skus/sku-details/sku-details.component.ts
import { Component, Input, SimpleChanges } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { DataService } from '../../../shared/services/data.service';
import { ProductsService } from '../../product/products.service';
import { Country } from '../../../shared/models/countryOriginModel';
import { CommodityCode } from '../../../shared/models/commodityCodeModel';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { layoutSkus } from '../../../shared/models/layoutTemplateModel';
import { SkusService } from '../skus.service';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { CompetitorItem } from '../../../shared/models/competitorModel';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { ItemModel, ItemModelResponse } from '../../../shared/models/itemModel';
import { Router } from '@angular/router';
import { NzUploadChangeParam, NzUploadModule } from 'ng-zorro-antd/upload';
import { ApiResponse } from '../../../shared/models/generalModel';
import { AttributeModel } from '../../../shared/models/attributeModel';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { AttributesValuesComponent } from '../../attributes/attributes-values/attributes-values.component';

@Component({
  selector: 'cousins-sku-details',
  imports: [ FormsModule,
             ReactiveFormsModule,
             NzInputModule,
             NzFormModule,
             NzSelectModule,
             NzCheckboxModule,
             NzButtonModule,
             NzIconModule,
             NzUploadModule,
             NzModalModule,
             AttributesValuesComponent
  ],
  templateUrl: './sku-details.component.html',
  styleUrl: './sku-details.component.css'
})
export class SkuDetailsComponent {

   skuForm!: FormGroup;
   countries : Country[]= [];
   layoutOptions: layoutSkus[] = [];
   commodityCode: CommodityCode[] = [];
   competitors: CompetitorItem[] = [];
   priceGroupItem: ItemModel[] = [];
   priceBreaks: ItemModel[] = [];
   pricingFormulas: ItemModel[] = [];
   selectedFileName: string = '';
   imagePreview: string | ArrayBuffer | null = null;
   savedAttributes: any[] = [];

  @Input() skuData!: any;
  addNewAttributeValueModal: boolean = false;
  attributeName: string = '';
  isLoadingAttributeNames: boolean = false;

  constructor(private fb: FormBuilder, private skusService: SkusService, private dataService: DataService,private router: Router) {
      this.skuForm = this.fb.group({
          akiProductID: [{ value: '' , disabled: true}],
          akiCategoryID: [{ value: '' , disabled: true}],
          akiSKUID: [{ value: '' , disabled: true}],
          skuName: ['',[ Validators.required ]],
          akiSKUDescription: [''],
          akiManufacturerRef: [''],
          akiitemid: [''],
          akiListOrder: [''],
          akiObsolete: [false],
          akiWebActive: [false],
          akiCurrentlyPartRestricted: [false],
          akiImageURL: [''],
          akiCommodityCode: [''],
          akiCountryOfOrigin: [''],
          akiSKUIsActive: [false],
          akiGuidePriceTBC: [10],
          akiGuideWeightTBC: [0],
          akiAlternativeTitle: [''],
          akiLayoutTemplate: [''],
          akiCompetitors: [''],
          akiPriceBreak: [''],
          akiPriceGroup: [''],
          akiPricingFormula: [''],

      });
  }

  ngOnInit() {
    this.getLayoutTemplate();
    this.getCommodityCodes();
    this.getCountryOrigin();
    this.getCompetitorDetails();
    this.getPriceGroupDetails();
    this.getPriceBreaksDetails();
    this.getPricingFormulasDetails();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['skuData']) {
      if (this.skuData) {
          this.skuForm.patchValue(this.skuData);
          this.getSkuAttributesBycategoryId();
      }
    }
  }

  getFormData() {
    return this.skuForm.getRawValue();
  }

  getCountryOrigin(){
    this.dataService.getCountryOrigin().subscribe({
      next:(response: Country[])=> {
          this.countries = response;
      },
      error: (err) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');  
      },
    })
  }
    
  getCommodityCodes(){
    this.dataService.getCommodityCodes().subscribe({
      next:(response: CommodityCode[])=> {
          this.commodityCode = response;
      },
      error: (err) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      },
    })
  }
  
  getLayoutTemplate() {
    this.skusService.getLayoutTemplateList().subscribe({
      next: (reponse: layoutSkus[]) => {
        this.layoutOptions = reponse;
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      }
    });
  } 

  getCompetitorDetails() {
    this.skusService.getCompetitorDetails().subscribe({
      next: (reponse: CompetitorItem[]) => {
        this.competitors = reponse;
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      }
    });
  } 

  getPriceGroupDetails() {
    this.skusService.getPriceGroupDetails().subscribe({
      next: (reponse: ItemModelResponse) => {
        if (reponse.isSuccess) {
            this.priceGroupItem = reponse.value;
        } else {
          this.dataService.ShowNotification('error', '',  reponse.exceptionInformation);
        }
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      }
    });
  }

  getPriceBreaksDetails() {
    this.skusService.getPriceBreaksDetails().subscribe({
      next: (reponse: ItemModelResponse) => {
        if (reponse.isSuccess) {
            this.priceBreaks = reponse.value;
        } else {
          this.dataService.ShowNotification('error', '',  reponse.exceptionInformation);
        }
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      }
    });
  }

  getPricingFormulasDetails() {
    this.skusService.getPricingFormulasDetails().subscribe({
      next: (reponse: ItemModelResponse) => {
        if (reponse.isSuccess) {
            this.pricingFormulas = reponse.value;
        } else {
          this.dataService.ShowNotification('error', '',  reponse.exceptionInformation);
        }
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
      }
    });
  }
  
  onFileSelected(event: NzUploadChangeParam) {
    const file = event.file?.originFileObj;
       if (file) {
        this.selectedFileName = file.name;
        // Show Preview
        const reader = new FileReader();
        reader.onload = () => {
          this.imagePreview = reader.result;
      };
      this.skuForm.get('akiImageURL')?.setValue( this.selectedFileName); // Set it immediately
  
      reader.readAsDataURL(file);

      if (event.file.status === 'uploading') {
        this.dataService.ShowNotification('success','', 'file uploaded successfully');
      }      
   }
  }

  goToLinkMaintenance(): void {
    if (!this.skuForm.getRawValue().akiSKUID) return;
    this.router.navigate(['/skus/link-maintenance']);
  }

  goToAdditionalImage(): void {
    if (!this.skuForm.getRawValue().akiSKUID) return;
    this.router.navigate(['/skus/additional-images']);
  }

  getSkuAttributesBycategoryId() {
    this.isLoadingAttributeNames = true;
    this.skusService.getSkuAttributesBycategoryId(this.getFormData().akiCategoryID).subscribe({
      next: (reponse: ApiResponse<AttributeModel[]>) => {
        if (reponse.isSuccess) {
          if (reponse && reponse.value.length > 0) {
            this.savedAttributes = reponse.value;
          }
        } else {
          this.dataService.ShowNotification('error', '',  reponse.exceptionInformation);
        }
        this.isLoadingAttributeNames = false;
      },
      error: (error) => {
        this.dataService.ShowNotification('error', '', 'Something went wrong');
        this.isLoadingAttributeNames = false;
      }
    });
  }

  showAddAttributesModal(attr: any) {
    this.attributeName = attr.attributeName
    this.addNewAttributeValueModal = true;
  }

  handleCancel() {
    this.addNewAttributeValueModal = false;
  }
  
  goToUploadForm() {
    const attributeNames: any = this.savedAttributes.map(item => item.attributeName);
    console.log('att ',attributeNames)
    sessionStorage.setItem('attributeNames', JSON.stringify(attributeNames));
    this.router.navigate(['/skus/attribute-multi-upload']);
  }
  

}

<div class="px-4">
    <form nz-form [formGroup]="skuForm">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12">
            <!-- Left Section -->
            <div class="lg:col-span-5 md:col-span-6">
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
    
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">Sku Id</nz-form-label>
                            <nz-form-control>
                                <input nz-input formControlName="akiSKUID" id="skuId" [disabled]="true"  />
                            </nz-form-control>
                        </nz-form-item>
    
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">Product Id</nz-form-label>
                            <nz-form-control>
                                <input nz-input formControlName="akiProductID" id="productId" [disabled]="true"  />
                            </nz-form-control>
                        </nz-form-item>
                    
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">Category Id</nz-form-label>
                            <nz-form-control >
                                <input nz-input formControlName="akiCategoryID" id="categoryId"  />
                            </nz-form-control>
                        </nz-form-item>
                    </div>
                    
                    <div class="grid grid-cols-1">
                        <nz-form-item>
                                <nz-form-label nzRequired [nzNoColon]="true" nzFor="skuName" [nzSm]="6" [nzXs]="24">Sku Name</nz-form-label>
                                <nz-form-control >
                                <div class="input-wrapper">
                                    <input nz-input formControlName="skuName" maxlength="100" />
                                    <span class="char-count">
                                        {{ 100 - skuForm.get('skuName')?.value?.length || 100 }}
                                    </span>
                                </div>
                                </nz-form-control>
                        </nz-form-item>
                    </div>
    
                    <div class="grid grid-cols-1">
                        <nz-form-item class="w-full">
                            <div class="flex flex-wrap justify-between items-center w-full mt-2">
                                <nz-form-label [nzNoColon]="true">SKu Description</nz-form-label>
                                <!-- <button nz-button nzType="default" class="border border-gray-300 px-3 py-1 rounded-md mr-8">
                                    Spelling
                                </button> -->
                            </div>
                            <nz-form-control >
                                <div class="input-wrapper">
                                <textarea nz-input formControlName="akiSKUDescription" maxlength="2000" class=""></textarea>
                                <span class="char-count">
                                    {{ 2000 - skuForm.get('akiSKUDescription')?.value?.length || 2000 }}
                                  </span>
                                  </div>
                            </nz-form-control>
                        </nz-form-item>
                    </div>
    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">Manufacturer Ref</nz-form-label>
                                <nz-form-control >
                                    <div class="input-wrapper">
                                        <input nz-input formControlName="akiManufacturerRef"/>
                                        <span class="char-count">
                                            {{ 50 - skuForm.get('akiManufacturerRef')?.value?.length || 50 }}
                                        </span> 
                                    </div>
                                </nz-form-control>
                        </nz-form-item>
    
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">Item Number</nz-form-label>
                                <nz-form-control >
                                    <div class="input-wrapper">
                                        <input nz-input formControlName="akiitemid" type="number"/>
                                        <span class="char-count">
                                            {{ 31 - skuForm.get('akiitemid')?.value?.length || 31 }}
                                        </span> 
                                    </div>
                                </nz-form-control>
                        </nz-form-item>
                    </div>
    
                    <div class="grid grid-cols-1 md:grid-cols-4 gap-2">
                        <nz-form-item>
                            <nz-form-label  [nzNoColon]="true">List Order</nz-form-label>
                            <nz-form-control >
                                <input nz-input formControlName="akiListOrder" type="number"/>
                            </nz-form-control>
                        </nz-form-item>
                    
                        <div class="nz-checkbox-wrapper nz-checkbox-wrapper-price">
                            <label formControlName="akiObsolete" nz-checkbox nzValue="false"> 
                                Obsolete
                            </label >
                        </div>
                        <div class="nz-checkbox-wrapper nz-checkbox-wrapper-price">
                            <label formControlName="akiWebActive" nz-checkbox nzValue="false"> 
                                Web Active
                            </label >
                        </div>
                        <div class="nz-checkbox-wrapper nz-checkbox-wrapper-price">
                            <label formControlName="akiCurrentlyPartRestricted" nz-checkbox nzValue="false"> 
                                Currently Part Restricted / Unavaliable
                            </label >
                        </div>  
                    </div>
    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-2"> 
                        <nz-form-item>
                            <nz-form-label nzFor="commodityCode"  [nzNoColon]="true">Commodity Code</nz-form-label>
                            <nz-form-control >
                                <!-- <input nz-input formControlName="akiProductCommodityCode" id="commodityCode"/> -->
                                <nz-select formControlName="akiCommodityCode" class="w-full" nzShowSearch nzAllowClear="true" >
                                    @for (commodity of commodityCode; track $index) {
                                        <nz-option  [nzValue]="commodity.commodityCode" [nzLabel]="commodity.commodityCode"></nz-option>
                                      }
                                </nz-select>
                            </nz-form-control>
                        </nz-form-item>
    
                        <nz-form-item>
                            <nz-form-label nzFor="countryOfOrigin"  [nzNoColon]="true">Country of Origin</nz-form-label>
                            <nz-form-control>
                                <nz-select formControlName="akiCountryOfOrigin" class="w-full" nzShowSearch="true" nzAllowClear="true">
                                    @for (country of countries; track $index) {
                                        <nz-option  [nzValue]="country.code" [nzLabel]="country.name"></nz-option>
                                    }
                                </nz-select>
                            </nz-form-control>
                        </nz-form-item>
                    </div>
    
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                        <nz-form-item class="col-span-2">
                            <nz-form-label [nzNoColon]="true" >Image URL</nz-form-label>
                                <nz-form-control [nzErrorTip]="'Please enter a valid URL'">
                                <div class="flex items-center space-x-2 relative">
                                    <input nz-input formControlName="akiImageURL" class="w-full" maxlength="255"/>
                                    <nz-upload
                                    nzAction=""
                                    [nzHeaders]="{ authorization: 'authorization-text' }"
                                    (nzChange)="onFileSelected($event)"
                                    [nzShowUploadList]="false"
                                    nzAccept=".png,.jpeg,.jpg"
                                >
                                    <button nz-button [nzType]="'primary'" class="m-0 px-4 text-white">                                            
                                         Upload
                                    </button>
                                </nz-upload>
                                    <span class="char-count">
                                    {{ 255 - skuForm.get('akiImageURL')?.value?.length || 255 }}
                                    </span> 
                                </div>
                                </nz-form-control> 
                        </nz-form-item>
    
                        <!-- No of Additional Images -->
                        <nz-form-item class="w-full">
                            <nz-form-label  nzFor="additionalImages" [nzNoColon]="true" class="product-link">
                                <a (click)="goToAdditionalImage()" class="underline">No of Additional Images</a>
                            </nz-form-label>
                            <nz-form-control>
                                <input nz-input  id="additionalImages" [disabled]="true"/>
                            </nz-form-control>
                        </nz-form-item>
                    </div>
    
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                        <!-- Image Height -->
                        <nz-form-item class="w-full">
                            <nz-form-label nzFor="guidePrice" [nzNoColon]="true">Guide Price</nz-form-label>
                            <nz-form-control>
                                <input nz-input formControlName="akiGuidePriceTBC" id="guidePrice" type="number" />
                            </nz-form-control>
                        </nz-form-item>
                    
                        <!-- Image Width -->
                        <nz-form-item class="w-full">
                            <nz-form-label nzFor="guideWeight" [nzNoColon]="true">Guide Weight</nz-form-label>
                            <nz-form-control>
                                <input nz-input formControlName="akiGuideWeightTBC" id="guideWeight" type="number" />
                            </nz-form-control>
                        </nz-form-item>
    
                         <!-- No of URL Links -->
                         <nz-form-item class="w-full">
                            <nz-form-label nzFor="urlLinks" [nzNoColon]="true" class="product-link">
                                <a (click)="goToLinkMaintenance()" class="underline">No of URL Links</a>
                            </nz-form-label>
                            <nz-form-control>
                                <input nz-input id="urlLinks" [disabled]="true" />
                            </nz-form-control>
                        </nz-form-item>
                    </div>     
    
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
                        <div class="grid grid-cols-1 col-span-2">
                            <nz-form-item class="w-full">
                                <nz-form-label [nzNoColon]="true">Attribute Names</nz-form-label>
                                <nz-form-control >
                                    <textarea nz-input  maxlength="2000" rows="4" class=""></textarea>
                                </nz-form-control>
                            </nz-form-item>
                        </div>
                        <div class="grid grid-cols-1 col-span-1 mt-6">
                            <button nz-button nzType="primary" class="text-white" >
                                Attribute Multi Upload
                            </button>
                         </div>
                    </div>
            </div>
        
            <!-- Right Section -->
            <div class="lg:col-span-5 md:col-span-6 lg:pl-20" >
                    <div class="mt-1">
                        <label >Catalogue Options</label>
                        <div class="border border-gray-300 rounded-lg p-3">
    
                            <div class="flex flex-col items-start space-y-2 nz-checkbox-wrapper nz-checkbox-wrapper-website">
                                <label class=""  formControlName="akiSKUIsActive" nz-checkbox nzValue="false">Cat Active </label >
                            </div>
    
                            <!-- Layout Template Dropdown -->
                            <nz-form-item class="w-full">
                                <nz-form-label nzFor="layoutTemplate" [nzNoColon]="true">Layout Template</nz-form-label>
                                <nz-form-control>
                                    <nz-select formControlName="akiLayoutTemplate" class="w-full" nzShowSearch="true" nzAllowClear="true">
                                        @for (option of layoutOptions; track option.templateCode) {
                                            <nz-option  [nzValue]="option.templateCode" [nzLabel]="option.layoutDescription"></nz-option>
                                        }
                                    </nz-select>
                                </nz-form-control>
                            </nz-form-item>
    
                            <!-- Alternative Title -->
                            <nz-form-item class="w-full">
                                <nz-form-label nzFor="alternativeTitle" [nzNoColon]="true">Alternative Title</nz-form-label>
                                <nz-form-control>
                                    <textarea nz-input rows="3" formControlName="akiAlternativeTitle" id="alternativeTitle" class="w-full"></textarea>
                                </nz-form-control>
                            </nz-form-item>
                        </div>
                    </div>
    
                    <div class="mt-1">
                        <label >Price Details</label>
                        <div class="border border-gray-300 rounded-lg p-3">
                            <div class="grid grid-cols-1 gap-1">
                                <nz-form-item>
                                    <nz-form-label  [nzNoColon]="true">Price Formula</nz-form-label>
                                    <nz-form-control >
                                        <nz-select formControlName="akiPricingFormula" class="w-full" nzShowSearch nzAllowClear="true">
                                            @for (option of pricingFormulas; track $index) {
                                                <nz-option  [nzValue]="option.code" [nzLabel]="option.description"></nz-option>
                                              }
                                        </nz-select>
                                    </nz-form-control>
                                </nz-form-item>
            
                                <nz-form-item>
                                    <nz-form-label  [nzNoColon]="true">Competitors</nz-form-label>
                                    <nz-form-control>
                                        <nz-select formControlName="akiCompetitors" class="w-full" nzShowSearch="true" nzAllowClear="true">
                                            @for (option of competitors; track $index) {
                                                <nz-option  [nzValue]="option.akiCompetitorID" [nzLabel]="option.akiCompetitorName"></nz-option>
                                            }
                                        </nz-select>
                                    </nz-form-control>
                                </nz-form-item>
                                
                                <nz-form-item>
                                    <nz-form-label  [nzNoColon]="true">Price Break</nz-form-label>
                                    <nz-form-control >
                                        <nz-select formControlName="akiPriceBreak" class="w-full" nzShowSearch nzAllowClear="true">
                                            @for (option of priceBreaks; track $index) {
                                                <nz-option  [nzValue]="option.code" [nzLabel]="option.description"></nz-option>
                                              }
                                        </nz-select>
                                    </nz-form-control>
                                </nz-form-item>
            
                                <nz-form-item>
                                    <nz-form-label [nzNoColon]="true">Price Group</nz-form-label>
                                    <nz-form-control>
                                        <nz-select formControlName="akiPriceGroup" class="w-full" nzAllowClear="true">
                                            @for (option of priceGroupItem; track $index) {
                                                <nz-option  [nzValue]="option.code" [nzLabel]="option.description"></nz-option>
                                            }
                                        </nz-select>
                                    </nz-form-control>
                                </nz-form-item>
                                
                            </div>
                        </div>
                    </div>
            </div>
        </div> 
    </form>
</div>

// CousinPCMS.React/src/components/skus/SKUDetails.tsx
import React, {useState, useEffect, useCallback} from 'react';
import {useNavigate} from 'react-router';
import {Form, Input, InputNumber, Select, Checkbox, Button, Upload, Modal, Spin} from 'antd';
import type {FormInstance} from 'antd/es/form';
import type {UploadChangeParam} from 'antd/es/upload';
import type {UploadFile} from 'antd/es/upload/interface';
import {getLayoutTemplateList, getCompetitorDetails, getPriceGroupDetails, getPriceBreaksDetails, getPricingFormulasDetails, getSkuAttributesBycategoryId} from '../../services/SkusService';
import {getCountryOrigin, getCommodityCodes} from '../../services/DataService';
import {useNotification} from '../../contexts.ts/useNotification';
import type {Country} from '../../models/countryOriginModel';
import type {CommodityCode} from '../../models/commodityCodeModel';
import type {layoutSkus} from '../../models/layoutTemplateModel';
import type {CompetitorItem} from '../../models/competitorModel';
import type {ItemModel} from '../../models/itemModel';
import type {SKuList} from '../../models/skusModel';
import type {AttributeModel} from '../../models/attributeModel';
import type {ApiResponse} from '../../models/generalModel';
import {ItemCharLimit} from '../../models/char.constant';
import AttributeValuesPopup from '../../components/attribute/AttributeValuesPopup';
interface SkuDetailsProps {
  skuData: SKuList | null;
  onFormInstanceReady: (form: FormInstance<SKuList>) => void;
}

interface SkuFormValues extends SKuList {
  additionalImages?: string;
  urlLinks?: string;
}

const SKUDetails: React.FC<SkuDetailsProps> = ({skuData, onFormInstanceReady}) => {
  const [form] = Form.useForm<SkuFormValues>();
  const navigate = useNavigate();

  const [countries, setCountries] = useState<Country[]>([]);
  const [layoutOptions, setLayoutOptions] = useState<layoutSkus[]>([]);
  const [commodityCode, setCommodityCode] = useState<CommodityCode[]>([]);
  const [competitors, setCompetitors] = useState<CompetitorItem[]>([]);
  const [priceGroupItem, setPriceGroupItem] = useState<ItemModel[]>([]);
  const [priceBreaks, setPriceBreaks] = useState<ItemModel[]>([]);
  const [pricingFormulas, setPricingFormulas] = useState<ItemModel[]>([]);

  const [savedAttributes, setSavedAttributes] = useState<AttributeModel[]>([]);
  const [isLoadingAttributeNames, setIsLoadingAttributeNames] = useState<boolean>(false);
  const [isAttributeValueModalVisible, setIsAttributeValueModalVisible] = useState<boolean>(false);
  const [selectedAttributeForModal, setSelectedAttributeForModal] = useState<AttributeModel | null>(null);

  const charLimit = ItemCharLimit;

  const skuName = Form.useWatch('skuName', form);
  const akiSKUDescription = Form.useWatch('akiSKUDescription', form);
  const akiManufacturerRef = Form.useWatch('akiManufacturerRef', form);
  const akiitemid = Form.useWatch('akiitemid', form);
  const akiImageURL = Form.useWatch('akiImageURL', form);
  const notify = useNotification();
  const fetchSkuAttributesByCategoryId = useCallback(async (categoryId: string | number) => {
    setIsLoadingAttributeNames(true);
    setSavedAttributes([]);
    try {
      const response: ApiResponse<AttributeModel[]> = await getSkuAttributesBycategoryId(String(categoryId));
      if (response.isSuccess && response.value) {
        setSavedAttributes(response.value);
      } else if (!response.isSuccess && response.exceptionInformation) {
        notify.warning(response.exceptionInformation);
      }
      console.log(`No attributes found for category ${categoryId} or request failed.`);
    } catch (error) {
      console.error('Error fetching SKU attributes:', error);
      notify.error('Failed to load SKU attributes.');
    } finally {
      setIsLoadingAttributeNames(false);
    }
  }, [notify]);

  useEffect(() => {
    onFormInstanceReady(form);
  }, [form, onFormInstanceReady]);
  useEffect(() => {
    const fetchDropdowns = async () => {
      try {
        const [countryRes, commRes, layoutRes, compRes, pgRes, pbRes, pfRes] = await Promise.all([
          getCountryOrigin(),
          getCommodityCodes(),
          getLayoutTemplateList(),
          getCompetitorDetails(),
          getPriceGroupDetails(),
          getPriceBreaksDetails(),
          getPricingFormulasDetails(),
        ]);

        setCountries(countryRes || []);
        setCommodityCode(commRes || []);
        setLayoutOptions(layoutRes || []);
        setCompetitors(compRes || []);
        setPriceGroupItem(pgRes?.isSuccess ? pgRes.value : []);
        setPriceBreaks(pbRes?.isSuccess ? pbRes.value : []);
        setPricingFormulas(pfRes?.isSuccess ? pfRes.value : []);
      } catch (error) {
        console.error('Error fetching dropdown data:', error);
        notify.error('Failed to load some form options.');
      }
    };
    fetchDropdowns();
  }, [notify]);
  useEffect(() => {
    if (skuData) {
      form.resetFields();
      form.setFieldsValue({
        ...skuData,
        akiObsolete: !!skuData.akiObsolete,
        akiWebActive: !!skuData.akiWebActive,
        akiCurrentlyPartRestricted: !!skuData.akiCurrentlyPartRestricted,
        akiSKUIsActive: !!skuData.akiSKUIsActive,
        additionalImages: String((skuData as {additionalImagesCount?: number}).additionalImagesCount || 0),
        urlLinks: String((skuData as {urlLinksCount?: number}).urlLinksCount || 0),
      });

      if (skuData.akiCategoryID) {
        fetchSkuAttributesByCategoryId(skuData.akiCategoryID);
      } else {
        setSavedAttributes([]);
      }
    } else {
      form.resetFields();
      setSavedAttributes([]);
    }
  }, [skuData, form, fetchSkuAttributesByCategoryId]);
  const handleFileChange = (info: UploadChangeParam<UploadFile>) => {
    const file = info.file?.originFileObj;
    if (file) {
      form.setFieldsValue({akiImageURL: file.name});
      if (info.file.status === 'uploading') {
        console.log('Uploading...');
      } else if (info.file.status === 'done') {
        notify.success(`${info.file.name} file uploaded successfully (simulated)`);
      } else if (info.file.status === 'error') {
        notify.error(`${info.file.name} file upload failed.`);
      }
    } else if (info.file.status === 'removed') {
      form.setFieldsValue({akiImageURL: ''});
    }
  };

  const handleShowAttributeValueModal = (attribute: AttributeModel) => {
    setSelectedAttributeForModal(attribute);
    setIsAttributeValueModalVisible(true);
  };

  const handleAttributeValueModalClose = () => {
    setIsAttributeValueModalVisible(false);
    setSelectedAttributeForModal(null);
  };

  const goToLinkMaintenance = () => {
    if (!skuData?.akiSKUID) return;
    navigate(`/SKUs/link-maintenance`);
  };

  const goToAdditionalImage = () => {
    if (!skuData?.akiSKUID) return;
    navigate(`/SKUs/additional-images`);
  };

  const goToUploadForm = () => {
    if (!savedAttributes || savedAttributes.length === 0) return;
    const attributeNames = savedAttributes.map((item) => item.attributeName);
    sessionStorage.setItem('attributeNames', JSON.stringify(attributeNames));
    navigate(`/skus/attribute-multi-upload`);
  };

  return (
    <div>
      <Form form={form} layout="vertical">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-x-10 gap-y-0">
          <div className="lg:col-span-6 md:col-span-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-x-3">
              <Form.Item label="Sku Id" name="akiSKUID">
                <Input disabled />
              </Form.Item>
              <Form.Item label="Product Id" name="akiProductID">
                <Input disabled />
              </Form.Item>
              <Form.Item label="Category Id" name="akiCategoryID">
                <Input disabled />
              </Form.Item>
            </div>

            <div className="relative">
              <Form.Item label="Sku Name" name="skuName" rules={[{required: true, message: 'SKU Name is required'}]}>
                <Input maxLength={charLimit.skuName} />
              </Form.Item>
              <span className="absolute -right-12 top-7 transform -translate-y-1/2  ">
                {skuName?.length || 0} / {charLimit.skuName}
              </span>
            </div>

            <div className="relative">
              <Form.Item label="SKu Description" name="akiSKUDescription">
                <Input.TextArea rows={3} maxLength={charLimit.akiSKUDescription} />
              </Form.Item>
              <span className="absolute bottom-2 -right-12">
                {akiSKUDescription?.length || 0} / {charLimit.akiSKUDescription}
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-2">
              <div className=" col-span-1 flex items-end gap-x-2">
                <Form.Item className="w-full" label="Manufacturer Ref" name="akiManufacturerRef">
                  <Input maxLength={charLimit.akiManufacturerRef} />
                </Form.Item>
                <span className="whitespace-nowrap">
                  {akiManufacturerRef?.length || 0} / {charLimit.akiManufacturerRef}
                </span>
              </div>
              <div className=" col-span-1 flex items-end gap-x-2">
                <Form.Item className="w-full" label="Item Number" name="akiitemid">
                  <Input maxLength={charLimit.akiitemid} />
                </Form.Item>
                <span className="whitespace-nowrap">
                  {String(akiitemid ?? '').length || 0} / {charLimit.akiitemid}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-2 items-end">
              <div className="col-span-1">
                <Form.Item className="col-span-2" label="List Order" name="akiListOrder">
                  <InputNumber min={0} style={{width: '100%'}} />
                </Form.Item>
              </div>
              <div className="col-span-1 flex items-end justify-between gap-x-2">
                <Form.Item name="akiObsolete" valuePropName="checked">
                  <Checkbox>Obsolete</Checkbox>
                </Form.Item>
                <Form.Item name="akiWebActive" valuePropName="checked">
                  <Checkbox>Web Active</Checkbox>
                </Form.Item>
                <Form.Item name="akiCurrentlyPartRestricted" valuePropName="checked">
                  <Checkbox>Part Restricted / Unavailable</Checkbox>
                </Form.Item>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-2">
              <Form.Item label="Commodity Code" name="akiCommodityCode">
                <Select
                  allowClear
                  showSearch
                  placeholder="Select code"
                  optionFilterProp="label"
                  options={commodityCode.map((c) => ({value: c.commodityCode, label: c.commodityCode, key: c.commodityCode}))}
                />
              </Form.Item>
              <Form.Item label="Country of Origin" name="akiCountryOfOrigin">
                <Select
                  allowClear
                  showSearch
                  placeholder="Select country"
                  optionFilterProp="label"
                  filterOption={(input, option) => (option?.label ?? '').toLowerCase().includes(input.toLowerCase())}
                  options={countries.map((c) => ({value: c.code, label: c.name, key: c.code}))}
                />
              </Form.Item>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-x-2 items-center">
              <div className="flex items-end space-x-2 col-span-2 ">
                <Form.Item label="Image URL" name="akiImageURL" className="w-full" rules={[{type: 'url', message: 'Please enter a valid URL'}]}>
                  <Input maxLength={charLimit.akiImageURL} />
                </Form.Item>
                <Upload
                  customRequest={(options) => setTimeout(() => options.onSuccess && options.onSuccess({}, options.file), 500)}
                  headers={{authorization: 'your-auth-token'}}
                  onChange={handleFileChange}
                  showUploadList={false}
                  accept=".png,.jpeg,.jpg"
                >
                  <Button type="primary">Upload</Button>
                </Upload>
                <span className=" whitespace-nowrap ">
                  {akiImageURL?.length || 0} / {charLimit.akiImageURL}
                </span>
              </div>
              <div className="col-span-1">
                <Form.Item
                  label={
                    <a onClick={goToAdditionalImage} className="underline cursor-pointer">
                      No of Additional Images
                    </a>
                  }
                  name="additionalImages"
                >
                  <Input disabled />
                </Form.Item>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-x-4 items-center">
              <Form.Item label="Guide Price" name="akiGuidePriceTBC">
                <InputNumber min={0} step={0.01} precision={2} style={{width: '100%'}} />
              </Form.Item>
              <Form.Item label="Guide Weight" name="akiGuideWeightTBC">
                <InputNumber min={0} step={0.01} precision={2} style={{width: '100%'}} />
              </Form.Item>
              <Form.Item
                label={
                  <a onClick={goToLinkMaintenance} className="underline cursor-pointer">
                    No of URL Links
                  </a>
                }
                name="urlLinks"
              >
                <Input disabled />
              </Form.Item>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-x-3 mt-2">
              <div className="md:col-span-2">
                <Form.Item label="Attribute Names" className="mb-0">
                  <Spin spinning={isLoadingAttributeNames}>
                    <div className="border border-border rounded-lg p-2 min-h-[60px]">
                      {savedAttributes.length > 0 ? (
                        savedAttributes.map((attr) => (
                          <div key={attr.attributeName}>
                            <a onClick={() => handleShowAttributeValueModal(attr)} className="text-primary-theme hover:underline">
                              {attr.attributeName}
                            </a>
                          </div>
                        ))
                      ) : (
                        <span className=" text-sm italic">{isLoadingAttributeNames ? 'Loading...' : 'No attributes found for this category.'}</span>
                      )}
                    </div>
                  </Spin>
                </Form.Item>
              </div>
              <div className="mt-auto mb-2 self-end">
                <Button type="primary" onClick={goToUploadForm} disabled={isLoadingAttributeNames || savedAttributes.length === 0} block>
                  Attribute Multi Upload
                </Button>
              </div>
            </div>
          </div>
          <div className="lg:col-span-5 md:col-span-6 lg:pl-10">
            <div className="mt-1">
              <label className="font-medium text-p block mb-1">Catalogue Options</label>
              <div className="border border-border rounded-lg p-3">
                <Form.Item name="akiSKUIsActive" valuePropName="checked" className="mb-3">
                  <Checkbox>Cat Active</Checkbox>
                </Form.Item>
                <Form.Item label="Layout Template" name="akiLayoutTemplate" className="mb-3">
                  <Select
                    allowClear
                    showSearch
                    placeholder="Select layout"
                    optionFilterProp="label"
                    options={layoutOptions.map((opt) => ({value: opt.templateCode, label: opt.layoutDescription, key: opt.templateCode}))}
                  />
                </Form.Item>
                <Form.Item label="Alternative Title" name="akiAlternativeTitle" className="mb-0">
                  <Input.TextArea rows={3} />
                </Form.Item>
              </div>
            </div>
            <div className="mt-4">
              <label className="font-medium text-primary-font block mb-1">Price Details</label>
              <div className="border border-border rounded-lg p-3">
                <div className="grid grid-cols-1 gap-y-3">
                  <Form.Item label="Price Formula" name="akiPricingFormula" className="mb-0">
                    <Select
                      allowClear
                      showSearch
                      placeholder="Select formula"
                      optionFilterProp="label"
                      options={pricingFormulas.map((opt) => ({value: opt.code, label: opt.description, key: opt.code}))}
                    />
                  </Form.Item>
                  <Form.Item label="Competitors" name="akiCompetitors" className="mb-0">
                    <Select
                      allowClear
                      showSearch
                      placeholder="Select competitor"
                      optionFilterProp="label"
                      options={competitors.map((opt) => ({value: opt.akiCompetitorID, label: opt.akiCompetitorName, key: opt.akiCompetitorID}))}
                    />
                  </Form.Item>
                  <Form.Item label="Price Break" name="akiPriceBreak" className="mb-0">
                    <Select allowClear showSearch placeholder="Select break" optionFilterProp="label" options={priceBreaks.map((opt) => ({value: opt.code, label: opt.description, key: opt.code}))} />
                  </Form.Item>
                  <Form.Item label="Price Group" name="akiPriceGroup" className="mb-0">
                    <Select
                      allowClear
                      showSearch
                      placeholder="Select group"
                      optionFilterProp="label"
                      options={priceGroupItem.map((opt) => ({value: opt.code, label: opt.description, key: opt.code}))}
                    />
                  </Form.Item>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Form>
      <Modal
        title={`Attribute Values for: ${selectedAttributeForModal?.attributeName || ''}`}
        open={isAttributeValueModalVisible}
        onCancel={handleAttributeValueModalClose}
        footer={null}
        width={600}
        destroyOnClose
        maskClosable={false}
      >
        {selectedAttributeForModal && skuData && (
          <AttributeValuesPopup attributeName={selectedAttributeForModal.attributeName} skuId={skuData.akiSKUID} itemNumber={skuData.akiitemid} onClose={handleAttributeValueModalClose} />
        )}
      </Modal>
    </div>
  );
};

export default SKUDetails;
