// CousinPCMS.React/src/components/shared/Header.tsx
import {useNavigate, useLocation} from 'react-router';

const Header = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const isActive = (path: string) => location.pathname.startsWith(path);
  return (
    <div className="bg-white absolute shadow-cousins-box overflow-hidden w-full">
      <ul className="flex gap-x-5 text-primary-font justify-end items-center py-2 px-6">
        <li className={`cursor-pointer ${isActive('/home') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/home')}>
          Home
        </li>
        <li className={`cursor-pointer ${isActive('/departments') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/departments')}>
          Departments
        </li>
        <li className={`cursor-pointer ${isActive('/category') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/category')}>
          Category
        </li>
        <li className={`cursor-pointer ${isActive('/products') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/products')}>
          Products
        </li>
        <li className={`cursor-pointer ${isActive('/skus') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/skus')}>
          SKUs
        </li>
        <li className={`cursor-pointer ${isActive('/attributes') ? 'text-primary-theme' : ''}`} onClick={() => navigate('/attributes')}>
          Attributes
        </li>
      </ul>
    </div>
  );
};

export default Header;

// CousinPCMS.Angular/src/app/components/shared/header/header.component.ts
import {Component} from '@angular/core';
import {Router, RouterLink} from '@angular/router';
import {NzDropDownModule} from 'ng-zorro-antd/dropdown';
import {NzMenuModule} from 'ng-zorro-antd/menu';
import {NavItem} from '../../../shared/models/generalModel';
import {TranslateModule} from '@ngx-translate/core';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'cousins-header',
  imports: [NzDropDownModule, NzMenuModule, RouterLink, TranslateModule, CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  constructor(private router: Router) {}
  navItems: NavItem[] = [
    {
      label: 'Home',
      path: '/home',
    },
    {
      label: 'Departments',
      path: '/departments',
    },
    {
      label: 'Category',
      path: '/category',
    },
    {
      label: 'Products',
      path: '/products',
    },
    {
      label: 'SKUs',
      path: '/skus',
    },
    {
      label: 'Attributes',
      path: '/attributes',
    },
  ];

  isActive(navItem: NavItem | {label: string; path: string}): boolean {
    const currentUrl = this.router.url;
    return currentUrl.startsWith(navItem.path);
  }
}


<header class="sticky top-0 z-50 w-full bg-white shadow-md">
  <div class="flex justify-end items-center shadow-cousins-box px-6 py-2 bg-white mb-4">
    <ul class="flex gap-x-10 items-center text-base font-medium my-1">
      @for (navItem of navItems; track $index) {
      <span class="cursor-pointer header" [routerLink]="[navItem.path]" [ngClass]="{'text-primary-theme font-semibold': isActive(navItem)}">
        {{ navItem.label | translate }}
      </span>
      }
    </ul>
  </div>
</header>
