// CousinPCMS.React/src/components/shared/LinkMaintenance.tsx
import React, {useState, useEffect, useCallback} from 'react';
import {useLocation} from 'react-router';
import {Button, Input, Select, Form, Spin, List, Popconfirm} from 'antd';
import {DeleteOutlined, MenuOutlined, QuestionCircleOutlined} from '@ant-design/icons';
import {getProductUrls, saveProductLinkUrl, deleteProductLinkUrl, updateProductLinkUrls} from '../../services/ProductService';
import {getCategoryUrls, saveCategoryLinkUrl, deleteCategoryLinkUrl, updateCategoryLinkUrls} from '../../services/CategoryService';
import {getSkuUrls, saveSkuLinkUrl, deleteSkuLinkUrl, updateSkuLinkUrls} from '../../services/SkusService';
import {useNotification} from '../../hook/useNotification';
import type {LinkValue, LinkRequestModel, LinkDeleteRequestModel, UpdateLinkOrderModel} from '../../models/linkMaintenanaceModel';
import type {ApiResponse} from '../../models/generalModel';
import {getSessionItem} from '../../services/DataService';
import {SortableContext, useSortable, verticalListSortingStrategy} from '@dnd-kit/sortable';
import {closestCenter, DndContext, PointerSensor, useSensor, useSensors} from '@dnd-kit/core';
import {CSS} from '@dnd-kit/utilities';
type ContextType = 'product' | 'category' | 'sku' | null;
const {Option} = Select;

const LinkMaintenance = () => {
  const [form] = Form.useForm();
  const [links, setLinks] = useState<LinkValue[]>([]);
  const [loadingData, setLoadingData] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const [displayText, setDisplayText] = useState<string>('');
  const [isDuplicateUrl, setIsDuplicateUrl] = useState<boolean>(false);

  const [contextId, setContextId] = useState<string | number | undefined>(undefined);
  const [contextType, setContextType] = useState<ContextType>(null);

  const location = useLocation();
  const notify = useNotification();
  const sensors = useSensors(useSensor(PointerSensor, {activationConstraint: {distance: 5}}));

  const fetchLinks = useCallback(
    async (id: string | number, type: 'product' | 'category' | 'sku') => {
      setLoadingData(true);
      setLinks([]);
      setDisplayText('');
      try {
        let response: ApiResponse<LinkValue[]>;
        switch (type) {
          case 'product':
            response = await getProductUrls(String(id));
            break;
          case 'category':
            response = await getCategoryUrls(String(id));
            break;
          case 'sku':
            response = await getSkuUrls(String(id));
            break;
          default:
            throw new Error('Invalid context type');
        }

        if (response.isSuccess && response.value) {
          // Ensure links are sorted by listorder if property exists
          const sortedLinks = response.value.sort((a, b) => (a.listorder || 0) - (b.listorder || 0));
          setLinks(sortedLinks);
          if (sortedLinks.length === 0) {
            setDisplayText('No links added yet.');
          }
        } else {
          setDisplayText('No Data.');
          if (response.exceptionInformation) notify.error(String(response.exceptionInformation));
        }
      } catch (error) {
        console.error('Error fetching links:', error);
        setDisplayText('Error loading links.');
        notify.error('Something went wrong while fetching links.');
      } finally {
        setLoadingData(false);
      }
    },
    [notify]
  );

  const handleContextAndFetchLinks = useCallback(() => {
    const path = location.pathname.toLowerCase();
    let id: string | number | undefined;
    let type: 'product' | 'category' | 'sku' | null = null;

    if (path.includes('/products')) {
      const idStr = getSessionItem('linkProductId');
      id = idStr ? Number(idStr) : undefined;
      type = 'product';
    } else if (path.includes('/category')) {
      id = getSessionItem('linkCategoryId');
      type = 'category';
    } else if (path.includes('/skus')) {
      id = getSessionItem('linkSkusId');
      type = 'sku';
    }

    setContextId(id);
    setContextType(type);

    if (id && type) {
      fetchLinks(id, type);
    } else {
      console.warn('Could not determine context or ID for link maintenance.');
      setLoadingData(false);
      setLinks([]);
      setDisplayText('Context ID not found.');
    }
  }, [location.pathname, fetchLinks]);

  useEffect(() => {
    handleContextAndFetchLinks();
  }, [handleContextAndFetchLinks]);

  const goBack = () => {
    sessionStorage.removeItem('linkProductId');
    sessionStorage.removeItem('linkCategoryId');
    sessionStorage.removeItem('linkSkusId');
    window.history.back();
  };

  const checkDuplicateUrl = (url: string | undefined | null) => {
    const inputValue = url?.trim().toLowerCase();
    const isDuplicate = links.some((link) => link.linkURL?.trim().toLowerCase() === inputValue);
    setIsDuplicateUrl(isDuplicate);
    return isDuplicate;
  };

  const handleUrlInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    checkDuplicateUrl(e.target.value);
  };

  const handleSave = async () => {
    if (!contextId || !contextType) {
      notify.error('Context ID or Type is missing.');
      return;
    }
    setLoading(true);
    try {
      const values = await form.validateFields();

      if (checkDuplicateUrl(values.linkURL)) {
        notify.error('This URL already exists.');
        setLoading(false);
        return;
      }

      const maxListOrder = links.length > 0 ? Math.max(...links.map((link) => link.listorder || 0)) : 0;
      const nextListOrder = maxListOrder + 1;

      const requestData: LinkRequestModel = {
        ...values,
        listorder: nextListOrder,
        productID: contextType === 'product' ? (contextId as number) : undefined,
        categoryID: contextType === 'category' ? contextId.toString() : undefined,
        skuItemID: contextType === 'sku' ? contextId.toString() : undefined,
      };
      let response: ApiResponse<string>;
      switch (contextType) {
        case 'product':
          response = await saveProductLinkUrl(requestData);
          break;
        case 'category':
          response = await saveCategoryLinkUrl(requestData);
          break;
        case 'sku':
          response = await saveSkuLinkUrl(requestData);
          break;
        default:
          throw new Error('Invalid context type for saving link');
      }

      if (response.isSuccess) {
        notify.success(`${contextType.charAt(0).toUpperCase() + contextType.slice(1)} Video link added successfully`);
        form.resetFields();
        setLinks((prev) => [...prev, requestData]);
      } else {
        notify.error('Failed to add link.');
      }
    } catch (errorInfo: any) {
      if (Array.isArray(errorInfo?.errorFields)) {
        notify.error('Please fill in all required fields correctly.');
      } else {
        console.error('An unexpected error occurred during save:', errorInfo);
        notify.error('Something went wrong during save.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteLink = async (linkToDelete: LinkValue) => {
    if (!contextId || !contextType) {
      notify.error('Context ID or Type is missing.');
      return;
    }

    setLoadingData(true);

    const req: LinkDeleteRequestModel = {
      linkURL: linkToDelete.linkURL,

      productID: contextType === 'product' ? (contextId as number) : undefined,
      categoryID: contextType === 'category' ? (contextId as string) : undefined,
      skuItemID: contextType === 'sku' ? (contextId as string) : undefined,
    };

    try {
      let response: ApiResponse<string>;
      switch (contextType) {
        case 'product':
          response = await deleteProductLinkUrl(req);
          break;
        case 'category':
          response = await deleteCategoryLinkUrl(req);
          break;
        case 'sku':
          response = await deleteSkuLinkUrl(req);
          break;
        default:
          throw new Error('Invalid context type for deleting link');
      }

      if (response.isSuccess) {
        notify.success(`${contextType.charAt(0).toUpperCase() + contextType.slice(1)} Video link successfully deleted.`);
        await handleContextAndFetchLinks();
      } else {
        notify.error('Failed to delete link.');
      }
    } catch {
      notify.error('Something went wrong during deletion.');
    } finally {
      setLoadingData(false);
    }
  };

  const getLinkIdByContext = (link: LinkValue, contextType: ContextType): number | undefined => {
    if (contextType === 'product') return link.producturlID;
    if (contextType === 'category') return link.categoryurlID;
    if (contextType === 'sku') return link.skuitemURLid;
  };

  // Function to handle drag end and persist order
  const handleLinkDragEnd = async ({active, over}: {active: any; over: any}) => {
    if (active.id !== over?.id) {
      const newIndex = links.findIndex((link) => getLinkIdByContext(link, contextType)?.toString() === over?.id?.toString());
      // Call API to persist new order
      setLoadingData(true);
      try {
        const link = links.find((links) => getLinkIdByContext(links, contextType)?.toString() === active.id?.toString());
        if (!link) {
          notify.error('Link not found.');
          setLoadingData(false);
          return;
        }

        const oldListOrder = link.listorder || 0;
        const newListOrder = links[newIndex]?.listorder || 0;

        const updateRequest: UpdateLinkOrderModel = {
          newlistorder: newListOrder,
          oldlistorder: oldListOrder,
          ...(contextType === 'product' && {productlinkid: link.producturlID}),
          ...(contextType === 'category' && {categoryurlID: link.categoryurlID}),
          ...(contextType === 'sku' && {skuitemURLID: link.skuitemURLid}),
        };
        let response: ApiResponse<string>;
        switch (contextType) {
          case 'product':
            response = await updateProductLinkUrls(updateRequest);
            break;
          case 'category':
            response = await updateCategoryLinkUrls(updateRequest);
            break;
          case 'sku':
            response = await updateSkuLinkUrls(updateRequest);
            break;
          default:
            throw new Error('Invalid context type for updating link order');
        }

        if (response.isSuccess) {
          handleContextAndFetchLinks();
          notify.success('Link order updated successfully.');
        } else {
          notify.error('Failed to update link order.');
        }
      } catch (error) {
        console.error('Error updating link order:', error);
        notify.error('Failed to update link order.');
      } finally {
        setLoadingData(false);
      }
    }
  };

  // Sortable Link Item component
  function SortableLinkItem({id, link, onDelete}: {id: string | number; link: LinkValue; onDelete: (link: LinkValue) => void}) {
    const {attributes, listeners, setNodeRef, transform, transition, isDragging} = useSortable({id});
    const style = {
      transform: CSS.Transform.toString(transform),
      transition,
      opacity: isDragging ? 0.5 : 1,
      background: isDragging ? '#f0f0f0' : undefined,
      cursor: 'grab',
      marginBottom: 0,
    };

    return (
      <div ref={setNodeRef} style={style} {...attributes} {...listeners} key={id}>
        <List.Item
          className="flex justify-between items-center px-2 py-1"
          actions={[
            <Popconfirm title="Delete this link?" onConfirm={() => onDelete(link)} okText="Yes" cancelText="No" placement="left" icon={<QuestionCircleOutlined style={{color: 'red'}} />}>
              <Button type="text" danger size="small" icon={<DeleteOutlined />} />
            </Popconfirm>,
          ]}
        >
          <span className="flex items-center flex-grow truncate">
            <Button type="text" size="small" icon={<MenuOutlined />} {...listeners} style={{cursor: 'grab', marginRight: 8}} className="drag-handle" />
            <span className="text-sm truncate" title={`(${link.linkURL})`}>
              {link.linkURL}
            </span>
          </span>
        </List.Item>
      </div>
    );
  }

  return (
    <div className="main-container">
      <div className="flex flex-wrap justify-between items-center p-4 pb-1">
        <span className="text-sm font-medium">Video Links</span>
        <Button type="default" onClick={goBack}>
          Close
        </Button>
      </div>
      <hr className="mt-2 mb-2 border-border" />
      <div className="p-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white p-4 border border-border rounded md:col-span-1">
            <div className="flex justify-between items-center mb-2">
              <label>Existing Links</label>
            </div>
            <Spin spinning={loadingData}>
              <div className="border border-border rounded divide-y divide-border max-h-[70vh] overflow-y-auto">
                {links.length > 0 ? (
                  <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleLinkDragEnd}>
                    <SortableContext items={[...links].sort((a, b) => (a.listorder || 0) - (b.listorder || 0)).map((img) => img.linkURL)} strategy={verticalListSortingStrategy}>
                      <ul style={{margin: 0, padding: 0}} className="divide-y divide-border">
                        {[...links]
                          .sort((a, b) => (a.listorder || 0) - (b.listorder || 0))
                          .map((link) => {
                            const key =
                              link.categoryurlID !== undefined
                                ? link.categoryurlID
                                : link.producturlID !== undefined
                                ? link.producturlID
                                : link.skuitemURLid !== undefined
                                ? link.skuitemURLid
                                : link.linkURL; // fallback to imageURL if none are present

                            return <SortableLinkItem key={key} id={key} link={link} onDelete={handleDeleteLink} />;
                          })}
                      </ul>
                    </SortableContext>
                  </DndContext>
                ) : (
                  <div className="flex justify-center items-center h-48 text-secondary-font">{displayText}</div>
                )}
              </div>
            </Spin>
          </div>

          <div className="border border-border rounded p-4 md:col-span-2 w-1/2">
            <label className="text-sm">Add New Video Links</label>
            <Form form={form} layout="vertical" className="space-y-2">
              <Form.Item label="Link Text" name="linkText" rules={[{required: true, message: 'Link Text is required.'}]}>
                <Input placeholder="e.g., View Datasheet" />
              </Form.Item>
              <Form.Item
                label="Link URL"
                name="linkURL"
                validateFirst
                rules={[
                  {required: true, message: 'Link URL is required.'},
                  {type: 'url', message: 'Please enter a valid URL.'},
                  {
                    validator: (_, value) => {
                      if (!value) return Promise.resolve();
                      return checkDuplicateUrl(value) ? Promise.reject('This URL already exists.') : Promise.resolve();
                    },
                  },
                ]}
              >
                <Input placeholder="https://example.com/datasheet.pdf" onChange={handleUrlInputChange} />
              </Form.Item>

              <Form.Item label="Tooltip" name="toolTip" rules={[{required: true, message: 'Tooltip is required.'}]}>
                <Input placeholder="e.g., Click to view PDF datasheet" />
              </Form.Item>

              <Form.Item label="Link Type" name="linkType" rules={[{required: true, message: 'Link Type is required.'}]}>
                <Select placeholder="Select type">
                  <Option value="Youtube">Youtube</Option>
                  <Option value="Web site">Web site</Option>
                </Select>
              </Form.Item>

              <Form.Item wrapperCol={{offset: 6, span: 18}}>
                <div className="flex justify-end gap-x-2">
                  <Button type="primary" onClick={handleSave} loading={loading} disabled={form.getFieldsError().some(({errors}) => errors.length > 0) || isDuplicateUrl}>
                    Save Link
                  </Button>
                </div>
              </Form.Item>
            </Form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LinkMaintenance;

// CousinPCMS.Angular/src/app/components/shared/link-maintenance/link-maintenance.component.ts
import {CommonModule, Location} from '@angular/common';
import {Component} from '@angular/core';
import {FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators} from '@angular/forms';
import {NzButtonModule} from 'ng-zorro-antd/button';
import {NzFormModule} from 'ng-zorro-antd/form';
import {NzIconModule} from 'ng-zorro-antd/icon';
import {NzInputModule} from 'ng-zorro-antd/input';
import {NzSelectModule} from 'ng-zorro-antd/select';
import {ProductsService} from '../../product/products.service';
import {DataService} from '../../../shared/services/data.service';
import {NzSpinModule} from 'ng-zorro-antd/spin';
import {Router} from '@angular/router';
import {Observable} from 'rxjs';
import {CategoryService} from '../../category/category.service';
import { LinkDeleteRequestModel, LinkRequestModel, LinkValue} from '../../../shared/models/linkMaintenanaceModel';
import { ApiResponse } from '../../../shared/models/generalModel';
import { SkusService } from '../../skus/skus.service';

@Component({
  selector: 'cousins-link-maintenance',
  imports: [ReactiveFormsModule, NzInputModule, NzButtonModule, NzFormModule, NzSelectModule, NzIconModule, CommonModule, NzSpinModule],
  templateUrl: './link-maintenance.component.html',
  styleUrl: './link-maintenance.component.css',
})
export class LinkMaintenanceComponent {

  links: LinkValue[] = [];
  showForm = false;
  linkForm!: FormGroup;

  displayText: string = '';
  loadingdata: boolean = false;
  loading: boolean = false;
  currentUrl: string = '';
  isDuplicateUrl = false;

  productId!: number | undefined;
  categoryId!: string | undefined;
  skuId!: string | undefined;

  constructor(
    private fb: FormBuilder,
    private location: Location,
    private productService: ProductsService,
    private dataService: DataService,
    private router: Router,
    private categoryService: CategoryService,
    private skusService: SkusService
  ) {
    this.linkForm = this.fb.group({
      linkText: ['', [Validators.required]],
      linkURL: ['', [Validators.required]],
      tooltip: ['', [Validators.required]],
      linkType: ['', [Validators.required]],
    });
  }

  ngOnInit(): void {
    this.currentUrl = this.router.url;
    if (this.currentUrl.includes('/products')) {
      const productIdStr = sessionStorage.getItem('productId');
      const productId: number | undefined = productIdStr ? +productIdStr : undefined;
      this.productId = productId;
      this.getProductLink();
    } else if (this.currentUrl.includes('/category')) {
      const categoryIdStr = sessionStorage.getItem('categoryId');
      const categoryId: string | undefined = categoryIdStr ? categoryIdStr : undefined;
      this.categoryId = categoryId;
      this.getCategoryLink();
    } else if (this.currentUrl.includes('/skus')) {
      const skuIdStr = sessionStorage.getItem('skuId');
      const skuId: string | undefined = skuIdStr ? skuIdStr : undefined;
      this.skuId = skuId;
      this.getSkusLink();
    }
  }

  cancel() {
    this.showForm = false;
  }

  goBack() {
    this.location.back();
    // sessionStorage.removeItem('productId');
    // sessionStorage.removeItem('categoryId');
    // sessionStorage.removeItem('skuId');
    
  }

  getProductLink() {
    this.loadingdata = true;
    const productId = sessionStorage.getItem('productId');
    this.handleGetApiResponse<ApiResponse<LinkValue[]>>(
      this.productService.getProductUrls(this.productId),
      (data: any) => {
        this.links = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
    
  }

  getCategoryLink() {
    this.loadingdata = true;
    this.handleGetApiResponse<ApiResponse<LinkValue[]>>(
      this.categoryService.getCategoryUrls(this.categoryId),
      (data: any) => {
        this.links = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
  }

  getSkusLink() {
    this.loadingdata = true;
    this.handleGetApiResponse<ApiResponse<LinkValue[]>>(
      this.skusService.getSkuUrls(this.skuId),
      (data: any) => {
        this.links = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
  }

  save() {
    if (!this.linkForm.valid) {
      this.dataService.ShowNotification('error', '', 'Please fill in all required fields.');
      return; // Stop the save process
    }
  
    if (this.currentUrl.includes('/products')) {
      this.loading = true;
      const requestData: LinkRequestModel = {
        ...this.linkForm.value,
        productID: this.productId
      };
      this.productService.saveProductLinkUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'LinkUrl Added Successfully');
            this.links.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'LinkUrl Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/category')) {
      this.loading = true;
      const requestData: LinkRequestModel = {
        ...this.linkForm.value,
        categoryID: this.categoryId
      };
      this.categoryService.saveCategoryLinkUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'LinkUrl Added Successfully');
            this.links.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'LinkUrl Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/skus')) {
      this.loading = true;
      const requestData: LinkRequestModel = {
        ...this.linkForm.value,
        skuItemID: this.skuId
      };
      this.skusService.saveSkuLinkUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'LinkUrl Added Successfully');
            this.links.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'LinkUrl Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    }
  }

  onAdd() {
    this.showForm = true;
    this.linkForm.reset();
  }

  deleteLink(data: LinkRequestModel, index: number) {
    this.loadingdata = true;
    const req: LinkDeleteRequestModel = {
      linkURL: data.linkURL,
    };
    if (this.currentUrl.includes('/products')) {
      this.productService.deleteProductLinkUrl({...req, productID: data.productID, }).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.links.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Product Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Product Url Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/category')) {
      this.categoryService.deleteCategoryLinkUrl({...req,  categoryID: data.categoryID,}).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.links.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Category Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Category Url Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/skus')) {
      this.skusService.deleteSkuLinkUrl({...req, skuItemID: data.skuItemID}).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.links.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Sku image Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Sku image Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    }
  } 

  handleGetApiResponse<T>(
    observable: Observable<T>,
    onSuccess: (data: T) => void,
    context: {
      loadingRef?: (state: boolean) => void;
      emptyCheck?: (data: any) => boolean;
      emptyMessage?: string;
      onEmpty?: () => void;
      onError?: () => void;
      notifyOnError?: boolean;
    } = {}
  ) {
    if (context.loadingRef) context.loadingRef(true);

    observable.subscribe({
      next: (response: any) => {
        if (context.loadingRef) context.loadingRef(false);

        if (response.isSuccess) {
          if (context.emptyCheck && context.emptyCheck(response.value)) {
            if (context.onEmpty) context.onEmpty();
          } else {
            onSuccess(response.value);
          }
        } else {
          if (context.onEmpty) context.onEmpty();
          if (context.notifyOnError) this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      },
      error: (err) => {
        if (context.loadingRef) context.loadingRef(false);
        if (context.onError) context.onError();
        if (context.notifyOnError) this.dataService.ShowNotification('error', '', 'Something went wrong');
      },
    });
  }

  checkDuplicateUrl(): void {
    const inputValue = this.linkForm.get('linkURL')?.value?.trim().toLowerCase();
  
    this.isDuplicateUrl = this.links.some(link =>
      link.linkURL?.trim().toLowerCase() === inputValue
    );
  }
}

<div class="bg-white rounded-lg m-5">
  <div class="flex justify-between items-center p-4 pb-1">
    <span>Link Maintenance</span>
    @if(!showForm) {
    <button nz-button nzType="primary" (click)="goBack()">Back</button>
    }
  </div>
  <hr class="mt-2 mb-2 border-light-border" />
  <div class="p-4">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <!-- Link List Section -->
      <div class="bg-white p-4">
        <!-- Header -->
        <div class="flex justify-between items-center mb-2">
          <label>Link for</label>
          <button nz-button nzType="primary" (click)="onAdd()">Add</button>
        </div>

        <!-- List -->
        <ul class="border-light-border border rounded divide-y divide-light-border max-h-[90%]">
          @if (loadingdata) {
          <div class="loading-container">
            <nz-spin nzSize="large"></nz-spin>
          </div>
          } @if (!loadingdata && links && links.length > 0) {
             @for(link of links; track $index) {
            <li class="flex justify-between items-center px-2 py-1 hover:bg-gray-50">
                <span class="text-secondary-font truncate">
                {{ link.linkURL }}
                </span>
                <button nz-button nzType="text" nzDanger (click)="deleteLink(link, $index)" class="ml-2">
                <nz-icon nzType="delete" class="text-danger" nzTheme="outline" />
                </button>
            </li>
            }
          <li class="h-20"></li>
          } @else if (!loadingdata) {
          <div class="flex justify-center items-center h-48">
            {{ displayText }}
          </div>
          }
        </ul>
      </div>

      <!-- Link Creator Section -->
       @if (showForm) {
        <div class="border-light-border border rounded mt-2 mb-2 p-4">
          <label class="block mb-2">Link Creator</label>
          <form nz-form [formGroup]="linkForm" class="space-y-4">
            <nz-form-item>
              <nz-form-label nzRequired [nzNoColon]="true" [nzSpan]="6">Link Text</nz-form-label>
              <nz-form-control [nzSpan]="18">
                <input nz-input formControlName="linkText" name="text" />
              </nz-form-control>
            </nz-form-item>
  
            <nz-form-item>
              <nz-form-label nzRequired [nzNoColon]="true" [nzSpan]="6">Link URL</nz-form-label>
              <nz-form-control [nzSpan]="18">
                <input nz-input formControlName="linkURL" name="url" (input)="checkDuplicateUrl()"/>
                @if (isDuplicateUrl) {
                  <div class="text-danger mt-1">
                    This URL already exists in the table.
                  </div>
                }
              </nz-form-control>
            </nz-form-item>
  
            <nz-form-item>
              <nz-form-label nzRequired [nzNoColon]="true" [nzSpan]="6">Tooltip</nz-form-label>
              <nz-form-control [nzSpan]="18">
                <input nz-input formControlName="tooltip" name="tooltip" />
              </nz-form-control>
            </nz-form-item>
  
            <nz-form-item>
              <nz-form-label nzRequired [nzNoColon]="true" [nzSpan]="6">Link Type</nz-form-label>
              <nz-form-control [nzSpan]="18">
                <nz-select formControlName="linkType" name="type">
                  <nz-option nzValue="Youtube" nzLabel="Youtube"></nz-option>
                  <nz-option nzValue="Web site" nzLabel="Web site"></nz-option>
                </nz-select>
              </nz-form-control>
            </nz-form-item>
  
            <div class="flex justify-end gap-2">
              <button nz-button (click)="cancel()">Cancel</button>
              <button nz-button nzType="primary" [disabled]="isDuplicateUrl" [nzLoading]="loading" (click)="save()">Save</button>
            </div>
          </form>
        </div>
       }
    </div>
  </div>
</div>
