// CousinPCMS.React/src/components/AdditionalImages.tsx
import React, {useState, useEffect, useRef, useCallback} from 'react';
import {useLocation} from 'react-router';
import {Button, Input, Spin, List, Popconfirm, Form, message} from 'antd';
import {DeleteOutlined, PlusOutlined, UploadOutlined, QuestionCircleOutlined} from '@ant-design/icons';
import type {ApiResponse} from '../models/generalModel';
import type {AdditionalImagesModel, AdditionalImageDeleteRequestModel} from '../models/additionalImagesModel';
import {getProductAdditionalImages, saveProductImagesUrl, deleteProductImagesUrl} from '../services/ProductService';
import {getCategoryAdditionalImages, saveCategoryImagesUrl, deleteCategoryImagesUrl} from '../services/CategoryService';
import {getSkuAdditionalImages, saveSkuImagesUrl, deleteSkuImagesUrl} from '../services/SkusService';
import {useNotification} from '../contexts.ts/useNotification';

const AdditionalImages: React.FC = () => {
  const [fileList, setFileList] = useState<AdditionalImagesModel[]>([]);
  const [showForm, setShowForm] = useState<boolean>(false);
  const [imageUrl, setImageUrl] = useState<string>('');
  const [avatarUrl, setAvatarUrl] = useState<string | ArrayBuffer | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [loadingData, setLoadingData] = useState<boolean>(false);
  const [displayText, setDisplayText] = useState<string>('');
  const [isDuplicateUrl, setIsDuplicateUrl] = useState<boolean>(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const location = useLocation();

  const [contextId, setContextId] = useState<string | number | undefined>(undefined);
  const [contextType, setContextType] = useState<'product' | 'category' | 'sku' | null>(null);
  const notify = useNotification();

  const fetchImages = useCallback(async (id: string | number, type: 'product' | 'category' | 'sku') => {
    setLoadingData(true);
    setFileList([]);
    setDisplayText('');
    try {
      let response: ApiResponse<AdditionalImagesModel[]>;
      switch (type) {
        case 'product':
          response = await getProductAdditionalImages(String(id));
          break;
        case 'category':
          response = await getCategoryAdditionalImages(String(id));
          break;
        case 'sku':
          response = await getSkuAdditionalImages(String(id));
          break;
        default:
          throw new Error('Invalid context type');
      }
      if (response.isSuccess && response.value) {
        setFileList(response.value);
        if (response.value.length === 0) {
          setDisplayText('No additional images found.');
        }
      } else {
        setDisplayText(response.exceptionInformation || 'Failed to load images.');
        if (response.exceptionInformation) notify.error(response.exceptionInformation);
      }
    } catch (error) {
      console.error(`Error fetching images for ${type} ${id}:`, error);
      setDisplayText('Error loading images.');
      notify.error('Something went wrong while fetching images.');
    } finally {
      setLoadingData(false);
    }
  }, [notify]);

  useEffect(() => {
    const path = location.pathname.toLowerCase();
    let id: string | number | undefined;
    let type: 'product' | 'category' | 'sku' | null = null;

    if (path.includes('/products')) {
      const idStr = sessionStorage.getItem('productId');
      id = idStr ? Number(idStr) : undefined;
      type = 'product';
    } else if (path.includes('/category')) {
      id = sessionStorage.getItem('categoryId') || undefined;
      type = 'category';
    } else if (path.includes('/skus')) {
      id = sessionStorage.getItem('skuId') || sessionStorage.getItem('itemNumber') || undefined;
      type = 'sku';
    }

    setContextId(id);
    setContextType(type);

    if (id && type) {
      fetchImages(id, type);
    } else {
      console.warn('Could not determine context or ID for additional images.');
      setLoadingData(false);
      setFileList([]);
      setDisplayText('Context ID not found.');
    }
  }, [location.pathname, fetchImages]);

  const goBack = () => {
    window.history.back();
  };

  const handleAddClick = () => {
    setImageUrl('');
    setAvatarUrl(null);
    setIsDuplicateUrl(false);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
    setShowForm(true);
  };

  const checkDuplicateUrl = (url: string) => {
    const inputValue = url?.trim().toLowerCase();
    const isDuplicate = fileList.some((file) => file.imageURL?.trim().toLowerCase() === inputValue);
    setIsDuplicateUrl(isDuplicate);
    return isDuplicate;
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const currentImageUrl = file.name;
      setImageUrl(currentImageUrl);
      checkDuplicateUrl(currentImageUrl);

      const reader = new FileReader();
      reader.onload = () => {
        setAvatarUrl(reader.result);
      };
      reader.onerror = (error) => {
        console.error('Error reading file:', error);
        message.error('Error reading file for preview.');
      };
      reader.readAsDataURL(file);
    } else {
      setImageUrl('');
      setAvatarUrl(null);
      setIsDuplicateUrl(false);
    }
  };

  const handleUpload = async () => {
    if (!imageUrl || isDuplicateUrl || !contextId || !contextType) {
      if (!imageUrl) message.error('Please select an image file.');
      if (isDuplicateUrl) message.error('This image URL already exists.');
      if (!contextId || !contextType) message.error('Context (Product/Category/SKU) is missing.');
      return;
    }
    setLoading(true);
    const requestData: Partial<AdditionalImagesModel> = {
      imageURL: imageUrl,
      imagename: imageUrl.replace(/\.[^/.]+$/, ''),
    };
    try {
      let response: ApiResponse<string>;
      let saveData: AdditionalImagesModel;
      switch (contextType) {
        case 'product':
          saveData = {...requestData, productID: contextId as number} as AdditionalImagesModel;
          response = await saveProductImagesUrl(saveData);
          break;
        case 'category':
          saveData = {...requestData, categoryID: contextId as string} as AdditionalImagesModel;
          response = await saveCategoryImagesUrl(saveData);
          break;
        case 'sku':
          saveData = {...requestData, skuItemID: contextId as string} as AdditionalImagesModel;
          response = await saveSkuImagesUrl(saveData);
          break;
        default:
          throw new Error('Invalid context type for saving image');
      }
      if (response.isSuccess) {
        notify.success('Image Added Successfully');
        setFileList((prev) => [...prev, saveData]);
        setShowForm(false);
      } else {
        notify.error(response.exceptionInformation || 'Failed to add image.');
      }
    } catch (error) {
      console.error(`Error saving image for ${contextType} ${contextId}:`, error);
      if (typeof error === 'object' && error && 'error' in error && typeof (error as {error?: {title?: string}}).error?.title === 'string') {
        notify.error((error as {error: {title: string}}).error.title);
      } else {
        notify.error('Something went wrong while saving the image.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteImage = async (imageToDelete: AdditionalImagesModel, index: number) => {
    if (!contextId || !contextType) {
      message.error('Context (Product/Category/SKU) is missing.');
      return;
    }
    setLoadingData(true);
    const reqBase: AdditionalImageDeleteRequestModel & {imagename?: string} = {
      imageURL: imageToDelete.imageURL,
      imagename: imageToDelete.imagename || imageToDelete.imageURL.replace(/\.[^/.]+$/, ''),
    };
    try {
      let response: ApiResponse<string>;
      switch (contextType) {
        case 'product':
          response = await deleteProductImagesUrl({...reqBase, productID: imageToDelete.productID});
          break;
        case 'category':
          response = await deleteCategoryImagesUrl({...reqBase, categoryID: imageToDelete.categoryID});
          break;
        case 'sku':
          response = await deleteSkuImagesUrl({...reqBase, skuItemID: imageToDelete.skuItemID});
          break;
        default:
          throw new Error('Invalid context type for deleting image');
      }
      if (response.isSuccess) {
        notify.success(`${contextType.charAt(0).toUpperCase() + contextType.slice(1)} image successfully deleted.`);
        setFileList((prevList) => prevList.filter((_, i) => i !== index));
      } else {
        notify.error(response.exceptionInformation || 'Failed to delete image.');
      }
    } catch (error) {
      console.error(`Error deleting image for ${contextType} ${contextId}:`, error);
      if (typeof error === 'object' && error && 'error' in error && typeof (error as {error?: {title?: string}}).error?.title === 'string') {
        notify.error((error as {error: {title: string}}).error.title);
      } else {
        notify.error('Something went wrong during deletion.');
      }
    } finally {
      setLoadingData(false);
    }
  };

  return (
    <div className="main-container">
      <div className="flex flex-wrap justify-between items-center p-4 pb-1">
        <span className="text-sm font-medium">Additional Images</span>
        <Button type="default" onClick={goBack}>
          Back
        </Button>
      </div>
      <hr className="mt-2 mb-2 border-border" />
      <div className="p-4">
        <div className="grid grid-cols-1 lg:grid-cols-3 md:grid-cols-2 gap-4">
          <div className="bg-white p-4 border border-border rounded lg:col-span-1 md:col-span-1">
            <div className="flex justify-between items-center mb-2">
              <label className="font-medium">Current Images</label>
              <Button type="primary" onClick={handleAddClick} size="small">
                Add
              </Button>
            </div>
            <Spin spinning={loadingData}>
              <div className="border border-border rounded divide-y divide-border max-h-[60vh] overflow-y-auto">
                {fileList.length > 0 ? (
                  <List
                    size="small"
                    dataSource={fileList}
                    renderItem={(image, index) => (
                      <List.Item
                        key={`${image.imageURL}-${index}`}
                        className="flex justify-between items-center px-2 py-1"
                        actions={[
                          <Popconfirm
                            title="Delete this image?"
                            onConfirm={() => handleDeleteImage(image, index)}
                            okText="Yes"
                            cancelText="No"
                            placement="left"
                            icon={<QuestionCircleOutlined style={{color: 'red'}} />}
                          >
                            <Button type="text" danger size="small" icon={<DeleteOutlined />} />
                          </Popconfirm>,
                        ]}
                      >
                        <span className="text-sm  truncate" title={image.imageURL}>
                          {image.imageURL}
                        </span>
                      </List.Item>
                    )}
                  />
                ) : (
                  <div className="flex justify-center items-center h-48">{displayText}</div>
                )}
              </div>
            </Spin>
          </div>

          {showForm && (
            <div className="p-4 border border-border rounded lg:col-span-2 md:col-span-1">
              <label className="block mb-2 font-medium">Add New Image</label>
              <div className="p-4 space-y-6">
                <Form layout="vertical">
                  <Form.Item label="Image URL / Filename" required validateStatus={isDuplicateUrl ? 'error' : ''} help={isDuplicateUrl ? 'This image URL already exists.' : ''}>
                    <div className="flex items-end gap-x-2">
                      <Input value={imageUrl} name="imageUrl" readOnly placeholder="Select a file using Browse" />

                      <input type="file" ref={fileInputRef} className="hidden" onChange={handleFileSelect} accept="image/png, image/jpeg, image/jpg" />

                      <Button type="default" onClick={() => fileInputRef.current?.click()} icon={<UploadOutlined />}>
                        Browse
                      </Button>
                    </div>
                  </Form.Item>
                </Form>

                <div className="flex items-end gap-x-4">
                  <div className="w-[102px] h-[102px] border border-dashed border-border flex justify-center items-center rounded overflow-hidden bg-gray-50">
                    {avatarUrl ? <img src={avatarUrl as string} alt="Preview" className="max-w-full max-h-full object-contain" /> : <PlusOutlined style={{fontSize: '24px', color: '#999'}} />}
                  </div>

                  <Button type="primary" loading={loading} disabled={!imageUrl || isDuplicateUrl} onClick={handleUpload} className="self-end">
                    Save Image Link
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AdditionalImages;

// CousinPCMS.Angular/src/app/components/shared/additional-images/additional-images.component.ts
import {CommonModule, Location} from '@angular/common';
import {Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Router} from '@angular/router';
import {NzButtonModule} from 'ng-zorro-antd/button';
import {NzFormModule} from 'ng-zorro-antd/form';
import {NzIconModule} from 'ng-zorro-antd/icon';
import {NzInputModule} from 'ng-zorro-antd/input';
import {NzUploadChangeParam, NzUploadFile, NzUploadModule} from 'ng-zorro-antd/upload';
import {Observable, Observer} from 'rxjs';
import {ProductsService} from '../../product/products.service';
import {DataService} from '../../../shared/services/data.service';
import {CategoryService} from '../../category/category.service';
import {ApiResponse} from '../../../shared/models/generalModel';
import {AdditionalImagesModel, AdditionalImageDeleteRequestModel} from '../../../shared/models/additionalImagesModel';
import {NzSpinModule} from 'ng-zorro-antd/spin';
import {SkusService} from '../../skus/skus.service';

@Component({
  selector: 'cousins-additional-images',
  imports: [FormsModule, NzInputModule, NzButtonModule, NzFormModule, NzUploadModule, NzIconModule, CommonModule, NzSpinModule],
  templateUrl: './additional-images.component.html',
  styleUrl: './additional-images.component.css',
})
export class AdditionalImagesComponent {
  fileList: AdditionalImagesModel[] = [];

  showForm: boolean = false;
  imageUrl!: string;
  loading: boolean = false;
  avatarUrl?: string | ArrayBuffer | null = null;
  currentUrl: string = '';
  displayText: string = '';
  loadingdata: boolean = false;

  productId!: number | undefined;
  categoryId!: string | undefined;
  skuId!: string | undefined;
  isDuplicateUrl = false;

  constructor(
    private location: Location,
    private router: Router,
    private productService: ProductsService,
    private dataService: DataService,
    private categoryService: CategoryService,
    private skusService: SkusService
  ) {}

  ngOnInit(): void {
    this.currentUrl = this.router.url;
    if (this.currentUrl.includes('/products')) {
      const productIdStr = sessionStorage.getItem('productId');
      const productId: number | undefined = productIdStr ? +productIdStr : undefined;
      this.productId = productId;
      this.getProductImages();
    } else if (this.currentUrl.includes('/category')) {
      const categoryIdStr = sessionStorage.getItem('categoryId');
      const categoryId: string | undefined = categoryIdStr ? categoryIdStr : undefined;
      this.categoryId = categoryId;
      this.getCategoryImages();
    } else if (this.currentUrl.includes('/skus')) {
      const skuIdStr = sessionStorage.getItem('skuId');
      const skuId: string | undefined = skuIdStr ? skuIdStr : undefined;
      this.skuId = skuId;
      this.getSkusImages();
    }
  }

  cancel() {
    this.showForm = false;
  }

  goBack() {
    this.location.back();
    // sessionStorage.removeItem('productId');
    // sessionStorage.removeItem('categoryId');
    // sessionStorage.removeItem('skuId');
  }

  onAdd() {
    (this.avatarUrl = ''), (this.imageUrl = '');
    this.showForm = true;
  }

  getProductImages() {
    this.loadingdata = true;
    this.handleGetApiResponse<ApiResponse<AdditionalImagesModel[]>>(
      this.productService.getGetProductAdditionalImages(this.productId),
      (data: any) => {
        this.fileList = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
  }

  getCategoryImages() {
    this.loadingdata = true;
    this.handleGetApiResponse<ApiResponse<AdditionalImagesModel[]>>(
      this.categoryService.getGetCategoryAdditionalImages(this.categoryId),
      (data: any) => {
        this.fileList = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
  }

  getSkusImages() {
    this.loadingdata = true;
    this.handleGetApiResponse<ApiResponse<AdditionalImagesModel[]>>(
      this.skusService.getSkuAdditionalImages(this.skuId),
      (data: any) => {
        this.fileList = data;
      },
      {
        loadingRef: (state) => (this.loadingdata = state),
        emptyCheck: (data) => !data || data.length === 0,
        onEmpty: () => (this.displayText = 'No Data'),
        notifyOnError: true,
      }
    );
  }

  handleGetApiResponse<T>(
    observable: Observable<T>,
    onSuccess: (data: T) => void,
    context: {
      loadingRef?: (state: boolean) => void;
      emptyCheck?: (data: any) => boolean;
      emptyMessage?: string;
      onEmpty?: () => void;
      onError?: () => void;
      notifyOnError?: boolean;
    } = {}
  ) {
    if (context.loadingRef) context.loadingRef(true);

    observable.subscribe({
      next: (response: any) => {
        if (context.loadingRef) context.loadingRef(false);

        if (response.isSuccess) {
          if (context.emptyCheck && context.emptyCheck(response.value)) {
            if (context.onEmpty) context.onEmpty();
          } else {
            onSuccess(response.value);
          }
        } else {
          if (context.onEmpty) context.onEmpty();
          if (context.notifyOnError) this.dataService.ShowNotification('error', '', 'Something went wrong');
        }
      },
      error: (err) => {
        if (context.loadingRef) context.loadingRef(false);
        if (context.onError) context.onError();
        if (context.notifyOnError) this.dataService.ShowNotification('error', '', 'Something went wrong');
      },
    });
  }

  deleteImage(data: AdditionalImagesModel, index: number) {
    this.loadingdata = true;
    const req: AdditionalImageDeleteRequestModel = {
      imageURL: data.imageURL,
    };
    if (this.currentUrl.includes('/products')) {
      this.productService.deleteProductImagesUrl({...req, productID: data.productID}).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.fileList.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Product image Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Product images Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/category')) {
      this.categoryService.deleteCategoryImagesUrl({...req, categoryID: data.categoryID}).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.fileList.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Category image Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Category image Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/skus')) {
      this.skusService.deleteSkuImagesUrl({...req, skuItemID: data.skuItemID}).subscribe({
        next: (response) => {
          if (response.isSuccess) {
            this.fileList.splice(index, 1);
            this.dataService.ShowNotification('success', '', 'Sku image Successfully Deleted');
          } else {
            this.dataService.ShowNotification('error', '', 'Sku image Failed Deleted');
          }
          this.loadingdata = false;
        },
        error: (err) => {
          this.loadingdata = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    }
  }

  uploadFile() {
    if (!this.imageUrl) {
      this.dataService.ShowNotification('error', '', 'Please select file.');
      return; // Stop the save process
    }
   
    if (this.currentUrl.includes('/products')) {
      this.loading = true;
      const requestData: AdditionalImagesModel = {
        imageURL: this.imageUrl,
        imagename: this.imageUrl.replace(/\.png$/i, ''),
        productID: this.productId
      };
      this.productService.saveProductImagesUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'Image Added Successfully');
            this.fileList.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'Image Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/category')) {
      this.loading = true;
      const requestData: AdditionalImagesModel = {
        imageURL: this.imageUrl,
        imagename: this.imageUrl.replace(/\.png$/i, ''),
        categoryID: this.categoryId,
      };
      this.categoryService.saveCategoryImagesUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'Image Added Successfully');
            this.fileList.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'Image Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    } else if (this.currentUrl.includes('/skus')) {
      const requestData: AdditionalImagesModel = {
        imageURL: this.imageUrl,
        imagename: this.imageUrl.replace(/\.png$/i, ''),
        skuItemID: this.skuId
      };
      this.loading = true;
      this.skusService.saveSkuImagesUrl(requestData).subscribe({
        next: (response: any) => {
          if (response.isSuccess) {
            this.dataService.ShowNotification('success', '', 'Image Added Successfully');
            this.fileList.push(requestData);
            this.showForm = false;
          } else {
            this.dataService.ShowNotification('error', '', 'Image Failed Add');
          }
          this.loading = false;
        },
        error: (err) => {
          this.loading = false;
          if (err?.error) {
            this.dataService.ShowNotification('error', '', err.error.title);
          } else {
            this.dataService.ShowNotification('error', '', 'Something went wrong');
          }
        },
      });
    }
  }

  onFileSelect(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.imageUrl = file.name;
      const reader = new FileReader();
      reader.onload = () => {
        this.avatarUrl = reader.result;
        this.imageUrl = file.name;
      };
      const inputValue = this.imageUrl?.trim().toLowerCase();
      this.isDuplicateUrl = this.fileList.some((file) => file.imageURL?.trim().toLowerCase() === inputValue);
      reader.readAsDataURL(file as unknown as File); // force cast for FileReader
    }
  }

  compressImage(file: File): Promise<string> {
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = (event: any) => {
        const img = new Image();
        img.src = event.target.result;
        img.onload = () => {
          const canvas = document.createElement('canvas');
          const maxWidth = 200;
          const scaleSize = maxWidth / img.width;
          canvas.width = maxWidth;
          canvas.height = img.height * scaleSize;
          const ctx = canvas.getContext('2d');
          ctx?.drawImage(img, 0, 0, canvas.width, canvas.height);
          resolve(canvas.toDataURL('image/jpeg', 0.7)); // quality 70%
        };
      };
      reader.readAsDataURL(file);
    });
  }

  beforeUpload = (file: NzUploadFile): boolean => {
    const rawFile = file as any;
    const inputValue = file.name?.trim().toLowerCase();
    this.isDuplicateUrl = this.fileList.some((file) => file.imageURL?.trim().toLowerCase() === inputValue);

    this.compressImage(rawFile as File).then((compressedBase64: string) => {
      this.avatarUrl = compressedBase64;
      this.imageUrl = file.name;
    });
    return false; // Prevent auto-upload
  };
}

<div class="bg-white rounded-lg m-5 overflow-auto max-h-[90vh]">
  <div class="flex flex-wrap justify-between items-center p-4 pb-1">
    <span>Additional Images</span>
    <button nz-button nzType="primary" (click)="goBack()">Back</button>
  </div>
  <hr class="mt-2 mb-2 border-light-border" />
  <div class="p-4">
    <div class="grid grid-cols-1 lg:grid-cols-3 md:grid-cols-2 gap-4 ">
      <!-- Link List Section -->
      <div class="bg-white p-4">
        <!-- Header -->
        <div class="flex justify-between items-center mb-2">
          <label>Additional Images</label>
          <button nz-button nzType="primary" (click)="onAdd()">Add</button>
        </div>

        <!-- List -->
        <ul class="border-light-border border rounded divide-y divide-light-border max-h-[60vh] overflow-y-auto">
          @if (loadingdata) {
            <div class="loading-container">
              <nz-spin nzSize="large"></nz-spin>
            </div>
          }  @if (!loadingdata && fileList && fileList.length > 0) {
            @for(image of fileList; track $index) {
            <li class="flex justify-between items-center px-2 py-1 hover:bg-gray-50">
              <span class="text-secondary-font truncate">
                {{ image.imageURL }}
              </span>
              <button nz-button nzType="text" nzDanger (click)="deleteImage(image, $index)" class="ml-2">
                <nz-icon nzType="delete" class="text-danger" nzTheme="outline" />
              </button>
            </li>
            }
          <li class="h-20"></li>
          } @else if (!loadingdata) {
            <div class="flex justify-center items-center h-48">
              {{ displayText }}
            </div>
            }
        </ul>
      </div>

       @if(showForm) {
        <div class="mb-2 p-4">
          <label class="block mb-2">Upload image to ftp site</label>
          <div class="border-light-border border rounded mt-2">
            <div class="p-4 space-y-6">
              
              <div class="w-full">
                <nz-form-item class="flex items-end gap-4">
                  <div class="flex-1">
                    <nz-form-label [nzNoColon]="true">Image URL</nz-form-label>
                    <nz-form-control>
                      <input nz-input [(ngModel)]="imageUrl" name="imageUrl" readonly required/>
                    </nz-form-control>
                  </div>
                  <input type="file" #fileInput class="hidden" (change)="onFileSelect($event)"/>
                  <button nz-button nzType="primary" (click)="fileInput.click()" class="mt-1">Browse</button>
                </nz-form-item>
                  @if (isDuplicateUrl) {
                    <div class="text-danger mt-1">
                      This Image already exists.
                    </div>
                  }
              </div>
              <div class="flex items-end">

                <nz-upload class="w-auto" nzListType="picture-card" [nzShowUploadList]="false" [nzBeforeUpload]="beforeUpload">
                  @if(!avatarUrl) {
                    <ng-container>
                      <div class="upload-box ">
                        <div class="flex justify-center items-center w-full h-full text-gray-400 text-xl">
                          <i nz-icon nzType="plus"></i>
                        </div>
                      </div>
                    </ng-container>
                  }
                  @if(avatarUrl) {
                    <ng-container>
                      <img [src]="avatarUrl" alt="image thumbnail" class="w-full max-w-[150px] max-h-[150px] rounded" />
                    </ng-container>
                  }
                </nz-upload>

                <!-- Upload Button -->
                <button class="mb-2" nz-button nzType="primary" [nzLoading]="loading" [disabled]="isDuplicateUrl" (click)="uploadFile()">Upload</button>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</div>
